### PR TITLE
Move Sauce key to JWT

### PR DESCRIPTION
**Pull request by ScottFreeCode**
I figure we'll test whether this works for a PR, then look at the branch and test whether it works for non-PR commits before merging into master, and if both those work then we can consider #2602 handled.

### CODE REVIEW

**Comment by ScottFreeCode** [comment]
Clearly I missed something, as this isn't getting all the Sauce credential stuff it's looking for: https://travis-ci.org/mochajs/mocha/jobs/179248317#L876

**Comment by ScottFreeCode** [comment]
Hmm. Even with `SAUCE_USERNAME` separately set, it's still getting this: https://travis-ci.org/mochajs/mocha/jobs/179251815#L876 Maybe it needs the `SAUCE_ACCESS_KEY` alone re-encrypted (because the old encrypted setting contained both)?

**Comment by dasilvacontin** [comment]
> Maybe it needs the SAUCE_ACCESS_KEY alone re-encrypted (because the old encrypted setting contained both)

Sounds likely!

**Comment by boneskull** [comment]
@ScottFreeCode `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` is *also* in the [settings](https://travis-ci.org/mochajs/mocha/settings) which may be conflicting?

**Comment by boneskull** [comment]
This is likely superceded by #2861.

**Pull request closed without merging**
