### PR TITLE
fix: better tracking of seen objects in error serialization

### LINKED ISSUE #4552: 🐛 Bug: Parallel mode crashes if test exception contains circular references
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

Parallel mode crashes or hangs if test exception contains circular references

#### 1. Hangs if error has self reference:

_Test file `test.js`_
```javascript
describe('Test', () => {
  it('test', () => {
    const error = new Error('Foo');
    error.self = error;
    throw error;
  });
});
```

Running following will simply hang:

```bash
$ mocha --parallel test.js
```

#### 2. Crashes if error has circular references passed within array properties

_Test file `test.js`_
```javascript
describe('Test', () => {
  it('test', () => {
    const error = new Error('Foo');
    error.foo = { props: [] };
    error.foo.props.push(error.foo);
    throw error;
  });
});
```

Running following

```bash
$ mocha --parallel test.js
```

will result with an error as:

```
 1) Uncaught error outside test suite

  0 passing (308ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'props' -> object with constructor 'Array'
    --- index 0 closes the circle
      at stringify (<anonymous>)
      at writeChannelMessage (node:internal/child_process/serialization:120:20)
      at process.target._send (node:internal/child_process:819:17)
      at process.target.send (node:internal/child_process:719:19)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Expected behavior:** 

Originally thrown exception should surface in report

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.2.1
- The output of `node --version`: 15.5.1
- Your operating system
  - name and version: macOS 10.15.7 
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh

### PR DESCRIPTION
**Pull request by sam-super**
### Description of the Change

Breaks circular references in before objects are serialized to prevent cryptic errors in parallel mode.
E.g. (taken from the linked issue):
```
 1) Uncaught error outside test suite

  0 passing (308ms)
  1 failing

  1) Uncaught error outside test suite:
     Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'props' -> object with constructor 'Array'
    --- index 0 closes the circle
      at stringify (<anonymous>)
      at writeChannelMessage (node:internal/child_process/serialization:120:20)
      at process.target._send (node:internal/child_process:819:17)
      at process.target.send (node:internal/child_process:719:19)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

For context we have seen this sort of error when using [nestjs](https://nestjs.com/) (e.g. when a module is missing a dependency, the error thrown contains a circular reference). It's likely something that would be good to fix in nestjs, but mocha would ideally handle it gracefully, regardless.

### Alternate Designs

We could just strip all 'extra' props of the Error object and keep only the standard parts (e.g. `message`,`name` and `stack`). Would need to make sure those props are what we expectthem to be. This would be more performant but at the cost of losing useful information on the error object.

### Why should this be in core?

Saves people from having to turn parallel mode off to work out why their test failed.

### Benefits

Errors that contain circular references can be more easily debugged.

### Possible Drawbacks

There is probably a performance penalty when inspecting the objects. The assumption is that it's not prohibitive.

### Applicable issues

This will be a fix/patch release

Fixes #4552

### CODE REVIEW

**Comment by sam-super** [comment]
Worth a re-run of the failing test?

**Comment by sam-super** [comment]
@Uzlopak looks like it might be a false positive. Windows tests ok for v14/v18 and i can't think of anything that might be low-level enough to affect just that set of versions.

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, nice and clean! ✨ 

@voxpelli I know you were looking at errors too, so I'd want to defer to your review on this one too.

**Comment by JoshuaKGoldberg** [comment]
FWIW @sam-super you don't need to keep merging in `main`, though I do appreciate the effort! 🙂 

I just wanted to wait a bit for a second review in case Pelle had time. That was time boxed till end of last week, so I'll go ahead and merge + release this now. Thanks again for the PR! 🙌

**Comment by JoshuaKGoldberg** [comment]
Published in [`mocha@10.5.2`](https://github.com/mochajs/mocha/releases/tag/v10.5.2). 🚀

**Comment by adrigzr** [comment]
Hello @sam-super @JoshuaKGoldberg, I have received the following exception randomly since this release. Do you know if it could be related to the change?

```
  1) Uncaught error outside test suite:
     Uncaught TypeError: this.parent.titlePath is not a function
      at Test.Runnable.titlePath (/node_modules/mocha/lib/runnable.js:217:22)
      at Test.Runnable.fullTitle (/node_modules/mocha/lib/runnable.js:206:15)
      at Test.serialize (/node_modules/mocha/lib/test.js:94:23)
      at SerializableEvent.serialize (/node_modules/mocha/lib/nodejs/serializer.js:256:27)
      at /node_modules/mocha/lib/nodejs/serializer.js:72:13
      at Array.forEach (<anonymous>)
      at SerializableWorkerResult.serialize (/node_modules/mocha/lib/nodejs/serializer.js:71:17)
      at serialize (/node_modules/mocha/lib/nodejs/serializer.js:366:15)
      at /node_modules/mocha/lib/nodejs/worker.js:127:28
      at ParallelBuffered.done (/node_modules/mocha/lib/nodejs/reporters/parallel-buffered.js:151:5)
```

**Comment by JoshuaKGoldberg** [comment]
Ah looks like it was! #5170

**Comment by JoshuaKGoldberg** [comment]
Ah looks like it was! #5170 cc @sam-super

**Comment by voxpelli** [comment]
Seems to have caused a regression: https://github.com/mochajs/mocha/issues/5188

**Pull request merged**
