### PR TITLE
Sort devDependencies alphabetically

### PR DESCRIPTION
**Pull request by outsideris**
In devDependencies, some modules isn't sorted alphabetically.

So, package.json will be updated whenever running `npm install`. It can make conflicts with others.

### CODE REVIEW

**Comment by juergba** [comment]
@outsideris These five devDependencies build a group:
```
    "@babel/preset-env": "7.12.17",
    "@babel/plugin-transform-regenerator": "7.12.1",
    "regenerator-transform": "0.14.5",
    "@babel/runtime": "7.12.5",
    "regenerator-runtime": "0.13.7",
```
I had to pin their versions in order to fix an `EvalError` when using Mocha in browser environment, see #4643.

> So, package.json will be updated whenever running npm install. It can make conflicts with others.

I don't understand this statement. _package.json_ isn't updated with `npm install` neither in windows nor Ubuntu.

So if this contribution just sorts devDependencies without any deeper reason, then IMO it does more harm than anything else.
Do you have any alternative proposition to solve this `async/await`/transpiling/`EvalError` problem?

**Comment by outsideris** [comment]
I didn't know about #4643 .

In macOs, `package.json` updated. 

```bash
$ git clone git@github.com:mochajs/mocha.git

$ cd mocha

$ npm i

added 2479 packages, and audited 2480 packages in 15s

24 vulnerabilities (4 low, 7 moderate, 13 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

$ git diff package.json
diff --git a/package.json b/package.json
index a645d2ad..117caed4 100644
--- a/package.json
+++ b/package.json
@@ -81,11 +81,9 @@
   "devDependencies": {
     "@11ty/eleventy": "^0.11.0",
     "@11ty/eleventy-plugin-inclusive-language": "^1.0.0",
-    "@babel/preset-env": "7.12.17",
     "@babel/plugin-transform-regenerator": "7.12.1",
-    "regenerator-transform": "0.14.5",
+    "@babel/preset-env": "7.12.17",
     "@babel/runtime": "7.12.5",
-    "regenerator-runtime": "0.13.7",
     "@mocha/docdash": "^3.0.1",
     "@rollup/plugin-babel": "^5.1.0",
     "@rollup/plugin-commonjs": "^14.0.0",
@@ -137,6 +135,8 @@
     "nyc": "^15.1.0",
     "pidtree": "^0.5.0",
     "prettier": "^1.19.1",
+    "regenerator-runtime": "0.13.7",
+    "regenerator-transform": "0.14.5",
     "remark": "^12.0.1",
     "remark-github": "^9.0.1",
     "remark-inline-links": "^4.0.0"
```

I didn't know `package.json` updated alphabetically only on macOS. 

I will check it why it happened.

**Comment by outsideris** [comment]
And `async/await/transpiling/EvalError` problem is related dependency order in `package.json`, not only versions?

**Comment by juergba** [comment]
> And `async/await/transpiling/EvalError` problem is related dependency order in package.json, not only versions?

I don't know. Btw I'm using npm v6.14.13.

**Comment by juergba** [comment]
@outsideris a new version v0.13.9 of _regenerator-runtime_ has been published a few days ago.
This could solve our `async/await/transpiling/EvalError` problem, I'm not sure though.
If yes, we could remove those version-pinned devDependencies again from our _package.json_.

**Comment by outsideris** [comment]
> This could solve our async/await/transpiling/EvalError problem, I'm not sure though.

@juergba Good news. I'm adding tests to prevent `async/await/transpiling/EvalError` problem. 
I'm not sure that I understand the problem exactly, I will submit a PR with the tests as draft. And I will test `regenerator-runtime` as well.

**Pull request closed without merging**
