### PR TITLE
Support `--inspect-brk` on command-line

### PR DESCRIPTION
**Pull request by igwejk**
There's already a support for `--inspect` option. This extends that support for the option, `--inspect-brk`.

### CODE REVIEW

**Comment by ORESoftware** [comment]
Just curious, what's the difference between

--inspect-brk and --inspect --debug-brk

is that the same?

**Comment by igwejk** [comment]
On `--inspect` and `--inspect-brk`, citing [Node.js v7.9.0 Documentation](https://nodejs.org/api/debugger.html#debugger_advanced_usage):

> V8 Inspector integration allows attaching Chrome DevTools to Node.js instances for debugging and profiling. It uses the [Chrome Debugging Protocol](https://chromedevtools.github.io/debugger-protocol-viewer/).
> 
> V8 Inspector can be enabled by passing the `--inspect` flag when starting a Node.js application. It is also possible to supply a custom port with that flag, e.g. `--inspect=9222` will accept DevTools connections on port 9222.
> 
> To break on the first line of the application code, pass the `--inspect-brk` flag instead of --`inspect`.

[Here](https://nodejs.org/api/debugger.html#debugger_tcp_based_protocol) the same documentation states the following about the `debug` option:

> The debug protocol used by the `--debug` flag was removed from V8.

In the general [deprecated section of the documentation](https://nodejs.org/api/deprecations.html#deprecations_dep0062_node_debug), the `--debug` feature is defined as

> `--debug` activates the legacy V8 debugger interface, which has been removed as of V8 5.8. It is replaced by Inspector which is activated with `--inspect` instead.

**Summary**
`--debug` and `--inspect` work enable similar features to the enduser, except that either of them use different protocols to deliver their functionality and that the `--debug` option has been marked for deprecation by Node.

Both `--debug` and `--inspect` have an associated `--debug-brk` and `--inspect-brk` which enables the debugger to break on the first line and allows you an opportunity to attach an external debugger to your application's node process.

**Comment by dasilvacontin** [comment]
@ScottFreeCode nothing extra afaik.

**Comment by ScottFreeCode** [comment]
Thanks for the update!

**Comment by dasilvacontin** [comment]
This enhancement has been released in [v3.3.0](https://github.com/mochajs/mocha/releases/tag/v3.3.0)! 🎉

**Pull request merged**
