### PR TITLE
fix uncaught TypeError if error occurs on next tick, closes #2315

### LINKED ISSUE #2315: Uncaught TypeError: Cannot read property 'currentRetry' of undefined
Tested on Mocha 2.5.3.

When uncaught error is thrown during "before" phase additional "Uncaught TypeError: Cannot read property 'currentRetry' of undefined" error is thrown from mocha.

Simple test case:
```js
'use strict';

describe('test', function () {
    before(function () {
        require('http').createServer().listen(1);
    });

    it('something', function () {
    });
});
```

output:
```
  test
    1) "before all" hook

  2) Uncaught error outside test suite

  0 passing (27ms)
  2 failing

  1) test "before all" hook:
     Uncaught Error: listen EACCES 0.0.0.0:1
      at Object.exports._errnoException (util.js:953:11)
      at exports._exceptionWithHostPort (util.js:976:20)
      at Server._listen2 (net.js:1240:19)
      at listen (net.js:1289:10)
      at Server.listen (net.js:1385:5)
      at Context.<anonymous> (test/test.js:5:40)

  2) test Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
```

### PR DESCRIPTION
**Pull request by 1999**

### CODE REVIEW

**Comment by 1999** [comment]
Just merged from upstream/master + rebased

**Comment by ljharb** [comment]
Getting this merged and released would help avoid hundreds of flaky test failures in our codebase every day - any update on getting this in?

**Comment by boneskull** [comment]
@ljharb it'll go in the next release, assuming it's OK, but I need to review it.

**Comment by boneskull** [comment]
@1999 lgtm, thanks!

**Comment by boneskull** [comment]
ugh, n/m, let me look into this further.  I'm so used to the appveyor failures being false alarms.

**Comment by boneskull** [comment]
I'm not really convinced this is the "right" way to fix the issue, but after some experimentation it seems to have the least amount of friction.

Main problem seems to be a flaky fixture which can evidently pass on Windows due to timing issues.  I have an experimental change in 4e88243919dbb56b081a22a81616c55ac41458b4 with build [here](https://ci.appveyor.com/project/boneskull/mocha/build/272).  If that has better results, I'll merge this and commit my change on top of it.

**Pull request merged**
