### PR TITLE
Add support --perf-basic-prof

### PR DESCRIPTION
**Pull request by robraux**
Very basic PR, adding support for --perf-basic-prof v8 option.
----
This supports creating flamegraphs on linux with mocha tests.

[Review on Reviewable](https://reviewable.io/reviews/mochajs/mocha/1963)

### CODE REVIEW

**Comment by robraux** [comment]
What would it take to get this merged?

**Comment by danielstjules** [comment]
Thanks for the PR! Maybe add it to `_mocha` so that it'll be in the usage options returned by `--help`

**Comment by robraux** [comment]
@danielstjules - updated to take into account `_mocha` usage options.

**Comment by robraux** [comment]
@danielstjules anything I can do to facilitate a merge here. I couldn't find anymore information on places to follow up re:mocha.

**Comment by danielstjules** [comment]
Sorry for the delay! Thanks again!

**Pull request merged**
