### PR TITLE
Add earl to a list of assertion libraries that works great with mocha

### PR DESCRIPTION
**Pull request by krzkaczor**
### Description of the Change

The documentation lists few assertion libraries: https://mochajs.org/#assertions. I want to add [earl](https://github.com/earl-js/earl) - assertion library that was created with Mocha in mind. (I am the author of earl).

### Benefits

Earl works great with TypeScript. As TypeScript becomes more and more popular in JS community, Mocha users will for sure look for assertion libraries that work well with TS.

### CODE REVIEW

**Comment by krzkaczor** [comment]
@boneskull @outsideris any chance to get this merged?

**Comment by juergba** [comment]
@krzkaczor I didn't add your library to our docs, but inserted your link to our [Wiki](https://github.com/mochajs/mocha/wiki#assertion-libraries) section.

**Comment by krzkaczor** [comment]
@juergba thanks for this! 

Any reason for not merging it to docs? I feel like 99% of people browse only the website :/

**Comment by juergba** [comment]
@krzkaczor it's a matter of time. We don't have time to evaluate/recommend third party packages.
Furthermore our docs are currently redesigned and will have a complete different look.

You can add a simple snapshot test case to our [mocha/samples](https://github.com/mochajs/mocha-examples), if you wish. This will draw additional attention to your package. Quite a few users are missing this feature in Mocha.

**Pull request closed without merging**
