### PR TITLE
[JSHINT] Unnecessary semicolon fixed in all files

### PR DESCRIPTION
**Pull request by ainthek**
if you don't mind, I have fixed also other files for this one bug.

May continue with other, or even include .jshintrc based on your style (if interested)

### CODE REVIEW

**Comment by dasilvacontin** [comment]
We are definitely interested in include style checks in our test/CI. I've been looking forward to suggest a .jshintrc over #1359, but I've been a bit busy lately. Could you come by the issue and suggest some settings?

**Comment by dasilvacontin** [comment]
(btw, you are using two different users in GitHub?)

**Comment by ainthek** [comment]
Hi felix, yes and sorry, I use several accounts depending where I sit and where I forget to change my git settings in keychain or display names in git config. Sorry again... hope it does not matter so much.

I vote for .jshint as, can make package.json changes, make npm run jslint script part of package json, and make jshint fitting your current style or take felines, well but what exactly do you prefer ?

**Comment by ainthek** [comment]
Ignore this pull request please, it fixes not source but generated file. Will make a new fix, sorry.

**Pull request closed without merging**
