### PR TITLE
Use process.browser in stackTraceFilter

### LINKED ISSUE #1764: Type check window instead of document to detect environment
I think it's generally accepted that to check whether an environment is node or browser, we should type check `window`, instead of `document`, because sometimes document is mocked for testing purpose.

### PR DESCRIPTION
**Pull request by berkerpeksag**
Closes #1764

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Ping. Is there anything I can do to help move this forward?

**Comment by boneskull** [comment]
If you can provide some kind of test output that would be great. 

I'm concerned this may be a breaking change. 

@mantoni I want to ensure this doesn't break your stuff, as my main concerns here are around how PhantomJS may react. We may want to test this branch against mochify before merging...

**Comment by mantoni** [comment]
Thanks for pinging me. At least browserify sets `process.browser = true` (see https://github.com/defunctzombie/node-process/blob/master/browser.js), so this shouldn't make a difference. In case of Mochify with PhantomJS I expect the path to result in `/`. I'm not entirely sure what WebDriver does with the location though ...

**Comment by georgecrawford** [comment]
Is there any movement on this one?

**Pull request closed without merging**
