### PR TITLE
Update TAP reporter. fix #2410

### LINKED ISSUE #2410: Improve tap reporter
It currently generates output like this:
```
1..1
ok 1 describe it
# tests 1
# pass 1
# fail 0
```

for

```js
describe('describe', () => {
  it('it', () => {
    expect(true).to.eql(true)
  })
})
```

It just flattens out `describe`s and prepends them the to test name.
This makes the `tap-spec` reporter unable to recognize test-cases.
```
echo '1..1\nok 1 Description\n# tests 1\n# pass 1\n# fail 0' >> test
cat test | node_modules/.bin/tap-spec
    ✔ Description


  ✖ No tests found
```

I think a viable alternative would be to print diagnostic messages for describe blocks.
```
1..1
# describe
ok 1 it
# tests 1
# pass 1
# fail 0
```
prints
```
>cat test | node_modules/.bin/tap-spec

  describe

    ✔ it


  total:     1
  passing:   1
  duration:  8ms
```
Nested describes should be concatened though I suppose.

### PR DESCRIPTION
**Pull request by apkiernan**
Updates the TAP reporter to print the `describe` blocks as diagnostic messages to allow for proper TAP output.

### CODE REVIEW

**Comment by apkiernan** [comment]
Each failure appears to be an issue with PhantomJS not installing correctly. Not sure how to remedy this

**Comment by Munter** [comment]
Did the behavior of the reporter also change from a streaming output to a buffer that is only flushed at the end?

**Comment by boneskull** [comment]
Yeah, it's not clear to me why we're buffering things now... @apkiernan ?

**Comment by apkiernan** [comment]
Apologies for the delay in responding, started a new job recently.

Looking back at this I think I had originally made the buffering change for testing purposes. I noticed the reassignment of console.log in another test and made the change to these tests as well so the buffering isn't needed. This has been changed back to streaming the output as it was originally.

**Comment by Munter** [comment]
Looks good to me.

I'm a bit confused about not seeing any tap reporter test output in the CI log. I'll see if I can have a look into that. Wouldn't want the tests to somehow not be run, now that we have them :)

**Pull request closed without merging**
