### PR TITLE
Fix 1766: stackfilter should not ignore node_modules

### PR DESCRIPTION
**Pull request by danielstjules**
Fix for https://github.com/mochajs/mocha/issues/1766

### CODE REVIEW

**Comment by jbnicolai** [comment]
:+1: from me.

**Comment by boneskull** [comment]
I'm on mobile so difficult to see--but if this ensures anything in Mocha's own `node_modules` is still hidden, go ahead and merge.

**Comment by danielstjules** [comment]
Weird. I don't remember merging this...

**Comment by jbnicolai** [comment]
@danielstjules I merged it, and amended the message to reference and close this issue. GH should be more transparant about this..

**Comment by danielstjules** [comment]
No worries, appreciate it! :)

**Comment by kpdecker** [comment]
Is this released? Just spent lost numerous hours fighting what I thought were source map issues only to finally find that it was this root issue.

**Comment by danielstjules** [comment]
Not yet, no. It will be in the next minor release

**Comment by kpdecker** [comment]
Thanks, I hacked around it locally for now. Completely understand the lag time between fix and release.

**Pull request closed without merging**
