### PR TITLE
Introduced comments to mocha.opts

### PR DESCRIPTION
**Pull request by danday74**
A line starting with // in mocha.opts will be treated as a comment.

If there is anything wrong with this PR then please advise. 

Many thanks.

Dan Lewis

### CODE REVIEW

**Comment by ScottFreeCode** [comment]
Hi @danday74, thanks for the PR! I especially appreciate the tests added here; we may adapt those even if we go with #2870 instead.

My gut instinct is that the comment indicator should be `#` (as in #2870) as in shell scripting because `mocha.opts` is just a list of commandline arguments. However, we'll need to look into potential compatibility issues with filenames (`mocha.opts` can specify the test file pattern/path), especially if may want to add we add end-of-line comment support (as discussed below). To my knowledge:
- double-slashes are valid in filepaths and can occur:
  - at the start of the path on some OSes where this indicates the path is on another machine (admittedly an unusual use case that would only show up in, say, a private and peculiar enterprise environment rather than something public and portable)
  - when a tool, program or user uses naive path concatenation to generate the path (e.g. joining `directory/` and `/filename.js` to `directory//filename.js`)
- `#` is valid in filenames, at the start or otherwise, but:
  - it is by convention reserved for special purposes such as Emacs' backup files

I could be wrong about some of those points and they may not be exhaustive, however; we may want to look for an expert in file name/path problems (or ask on Stack Exchange) for further info.

I'd also be curious whether we would want to support comments on the same line as options, e.g. `--compilers myspecialthing:path/to/mything # myspecialthing is really just a fork of CoffeeScript that fixes my pet peeves and adds my favorite feature from Elm or whatever`; in that case, ensuring that the regex does not begin with `^` would probably do -- although I also presume we could add comment support at the start of lines first and then later add comment support on the same line after options.

**Comment by danday74** [comment]
Many thanks for the feedback on this.

Happy if you decide in favour of [#2870](https://github.com/mochajs/mocha/pull/2870).

Also happy if you want me to make changes so that we can get this in. I'm very active so can make changes quickly and would be proud to be a contributor. Very experienced with unit testing too.

Re: // syntax

Interesting discussion on "naive path concatenation". Good thinking. We could ensure that the line starts with // OR that // is preceded by a space before considering it a comment?

Re: # syntax

Since filenames can also contain these, how about ensuring that the line starts with # OR that # is preceded by a space?

See also .. https://stackoverflow.com/questions/45742287/javascript-regex-to-distinguish-between-a-comment-and-a-file-path

Happy to change comment syntax from // to # (or support both?)

Happy also to add support for same line comments.

If you want me to take any action then please let me know, I am very keen, I love mocha :)

**Comment by danday74** [comment]
Can we take some action here?

**Comment by ScottFreeCode** [comment]
Hey @danday74, just a heads-up, there's some discussion going on at #2870 currently that may get us to where we can move forward with these decisions and merge these. Feel free to drop in any thoughts you have there!

**Comment by danday74** [comment]
Thanks for the heads up, have chipped in on #2870 as suggested :)

**Comment by igwejk** [comment]
@danday74 , I commend your effort very much.

Though, as you know already #2870 introduced support for comments in `mocha.opts`.

We should also take note that `bin/options.js` was refactored and tested fully in #2881.

Let's throw our weight behind the PRs that have prospectively improved mocha options instead of doing them all over in another PR.

**Comment by danday74** [comment]
agreed i will close this off

**Pull request closed without merging**
