### PR TITLE
CSS Smooth scrolling on fragment navigation

### PR DESCRIPTION
**Pull request by Munter**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

Add CSS smooth scrolling to documentation page. This is a progressive enhancement.

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
https://caniuse.com/#feat=css-scroll-behavior

### Benefits

This will possibly make it easier to understand what's happening when you navigate page internal fragment identifiers

### Possible Drawbacks

Might be annoying. We'll have to try it out

### CODE REVIEW

**Comment by Munter** [comment]
Looks like I read the documentation wrong. Doesn't seem to have any effect on the full browser viewport, only smaller boxes with explicit scrolling behavior :'(

**Comment by Munter** [comment]
There we go. I applied it to the wrong tag

**Comment by Munter** [comment]
Having tried it on the deployment preview I'm not a big fan of this technique for our use case

**Comment by boneskull** [comment]
@Munter Agree.  The page is just too long.  I'll close this...

**Pull request closed without merging**
