### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mochajs/mocha now has a Chat Room on Gitter

@boneskull has just created a chat room. You can visit it here: [https://gitter.im/mochajs/mocha](https://gitter.im/mochajs/mocha?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mochajs/mocha?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
+1

Envoyé de mon iPhone

**Comment by boneskull** [comment]
they stuffed it in the middle of `README.md`, seemingly randomly.  anyway...

**Comment by pkozlowski-opensource** [comment]
Oh dear, @gitter-badger is a bot and a spammy one from what I can see from its activity on other projects... I would expect better from a service that has any self-respect....

**Comment by gitter-badger** [comment]
That's ok @pkozlowski-opensource, I'll go back home to my den :(

**Pull request closed without merging**
