### PR TITLE
fix #1241

### LINKED ISSUE #1241: err.showDiff = true breaks string diffs
Observed:

    2)  should compare strings (raw):

        Error: bad stuff
        + expected - actual

        +"a\nb\nc\nd"
        -"a\nb\n"

Wanted:

    2)  should compare strings (raw):

        Error: bad stuff
        + expected - actual

         a
         b
        +c
        +d

Example code: (see https://github.com/felixrabe/mocha-chai-string-diff/blob/master/test/test.js for the complete example code, run with `mocha`)

    it('should compare strings (raw)', function() {
      var err = new Error('bad stuff');
      err.expected = 'a\nb\nc\nd';
      err.actual = 'a\nb\n';
      err.showDiff = true;  // breaks string diffs
      // err.showDiff = false;  // string diffs are fine
      throw err;
    });

With Chai:

    var expect = require('chai').expect;

    it('should compare strings (chai)', function() {
      try {
        expect('a\nb\n').to.equal('a\nb\nc\nd');
      } catch (err) {
        // string diffs broken because err.showDiff === true
        // err.showDiff = false;  // string diffs are fine
        throw err;
      }
    });

If you uncomment the `// err.showDiff = false;` lines (ie. if you set `showDiff` to `false`), string diffs show up fine.

### PR DESCRIPTION
**Pull request by arBmind**
perform stringify only if type is not string

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Dang. I'm willing to pass the torch on this one, if anybody wants to code the tests for `BaseReporter`. I already made some, and I can publish/link the branch somewhere in order to checkout from there.

**Comment by boneskull** [comment]
@dasilvacontin Don't worry about it, it'll be eviscerated w/ plugin api anyway

**Comment by boneskull** [comment]
oh, wait, this is a PR.

**Comment by dasilvacontin** [comment]
@boneskull, yeah, what I'm not so sure is how this plays along with your diff changes, or a rework you made a month/s ago.

**Comment by boneskull** [comment]
I'm going to have to close this due to conflicts.  @arBmind thanks for the contribution

**Pull request closed without merging**
