### PR TITLE
add new quiet reporter which disables console debugging

### PR DESCRIPTION
**Pull request by ozankasikci**
Hi, we needed to disable console debugging in our code, i guess some other people might need this feature as well so decided to contribute.

here is the demo:
Alt text

If you guys want some tests to be written, i can do that as well.

Thanks.

[Review on Reviewable](https://reviewable.io/reviews/mochajs/mocha/2084)

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR! Wouldn't it make more sense for the constructor to accept a second arg, options, which could include the logger?

**Comment by ozankasikci** [comment]
@danielstjules  :+1:  that's right, added second parameter to `Base` reporter constructor. `Base.list` still takes a second parameter since it's a static function, any objection to this?

also realized that in the previous version i didnt add the changes to `mocha.js` that is under root folder. added them this time.

**Comment by HansHammel** [comment]
exactly what I Need, but still not merged!?

**Comment by ScottFreeCode** [comment]
I'm surprised this works; I had the idea a while back to try hijacking/replacing console.log, unrelated to Mocha, and I got errors because Node wouldn't let me reassign `console.log = <new thing>`.

**Comment by okbel** [comment]
+1

**Comment by pmuens** [comment]
+1

**Comment by boneskull** [comment]
cannot merge w/o CLA signed; this is better as a third-party reporter. thanks

**Comment by vassudanagunta** [comment]
Use ['mocha-suppress-logs'](https://www.npmjs.com/package/mocha-suppress-logs). It is properly implemented using Mocha [Root Hook Plugins](https://mochajs.org/#root-hook-plugins) and works great.

**Pull request closed without merging**
