### PR TITLE
Change parseInt to bitOperator to increase performance

### PR DESCRIPTION
**Pull request by wnghdcjfe**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change
paseInt to bitOperator
forExample, 
before
parseInt(value, 10) 
after
value | 0

### Alternate Designs
because to change Decimal Number and to affect like Math.floor
but I think they didn't think bitOperator

###  Increase performance 30% faster than before
Hi I found it in the middle of an analysis mocha
parseInt(value, 10) is a function that transforms it into an integer like Math.floor.
But bitOperator is more than faster than that. 

For example, In D3.js, use bitOperator like this
```js
function shuffle(array, i0, i1) {
  var m = (i1 == null ? array.length : i1) - (i0 = i0 == null ? 0 : +i0),
      t,
      i;

  while (m) {
    i = Math.random() * m-- | 0;
    t = array[m + i0];
    array[m + i0] = array[i + i0];
    array[i + i0] = t;
  }

  return array;
}
```

and In JavaScript Performance comparing site,JSmatch said. bitOperator is 30% faster than parseInt
link : http://jindo.dev.naver.com/jsMatch/index.html?d=382&openResult=1 
 

### Benefits
Increase performance 30% faster than before

### Possible Drawbacks
No negative, only possible side

### CODE REVIEW

**Comment by wnghdcjfe** [comment]
And https://jsperf.com/parseintvsbitoperator said bitOperator performance 
I locally test 1000 times in mocha 
For Example, retrires("1.2345")... but the big Performance is not found
but I am sure that it is awesome to mocha.

**Comment by Munter** [comment]
I'm not a big fan of this as it reduces maintainability. I'd rather have ready to read source code.

**Comment by wnghdcjfe** [comment]
## test code
```js
const assert = require('assert');
const _ = require('lodash');

describe('retries', function() {
  // Retry all tests in this suite up to 4 times 
  for(let i = 0; i < 1000; i++){
    this.retries("4.121233");
    beforeEach(function() {
  
    });
  
    it('should succeed on the 3rd try', function() {
      // Specify this test to only retry up to 2 times
      this.retries("5.123"); 
    });
  } 
}); 
```
## orgin mocha version
```
time mocha ./test/index.js
real    0m2.903s
user    0m2.783s
sys     0m0.172s
```

## my mocha version
```
time node mocha/bin/mocha ./test/index.js
real    0m2.735s
user    0m2.681s
sys     0m0.163s
```

## result
 - real : -0.200s
 - user : -0.100s
 - sys :  -0.01s

faster than before

**Comment by wnghdcjfe** [comment]
> I'm not a big fan of this as it reduces maintainability. I'd rather have ready to read source code.

Bit operators do not reduce maintainability. Many open sources already use bit operators.
Moreover, Mocha also has a bit operator in its internal code.

**Comment by wnghdcjfe** [comment]
> I'm not a big fan of this as it reduces maintainability. I'd rather have ready to read source code.

And I will try hard to read the code. Thank you for your opinion

**Comment by wnghdcjfe** [comment]
## test code(2)
```js
const assert = require('assert');
const _ = require('lodash');

describe('retries', function() {
  // Retry all tests in this suite up to 4 times 
  for(let i = 0; i < 1000; i++){
    this.retries("4");
    beforeEach(function() {
  
    });
  
    it('should succeed on the 3rd try', function() {
      // Specify this test to only retry up to 2 times
      this.retries("5"); 
    });
  } 
}); 
```
## orgin mocha version
```
time mocha ./test/index.js
real    0m2.546s
user    0m2.591s
sys     0m0.153s
```

## my mocha version
```
time node mocha/bin/mocha ./test/index.js
real    0m2.391s
user    0m2.422s
sys     0m0.149s
```

## result
 - real : -0.155s
 - user : -0.169s
 - sys :  -0.004s

faster than before

**Comment by wnghdcjfe** [comment]
## test code(3)
```js
const assert = require('assert');
const _ = require('lodash');

describe('retries', function() {
  // Retry all tests in this suite up to 4 times 
  for(let i = 0; i < 1000; i++){
    this.retries(4);
    beforeEach(function() {
  
    });
  
    it('should succeed on the 3rd try', function() {
      // Specify this test to only retry up to 2 times
      this.retries(5); 
    });
  } 
}); 
```
## orgin mocha version
```
time mocha ./test/index.js
real    0m2.608s
user    0m2.610s
sys     0m0.158s
```

## my mocha version
```
time node mocha/bin/mocha ./test/index.js
real    0m2.483s
user    0m2.482s
sys     0m0.151s
```

## result
 - real : -0.125s
 - user : -0.128s
 - sys :  -0.07s

faster than before

**Comment by ORESoftware** [comment]
@wnghdcjfe  create an NPM package and once it's proven, Mocha can use it

**Comment by Munter** [comment]
One thing we could do is completely remove the first of the two instances of `parseInt` in this PR altogether. Literally 3 lines up is a guarantee that it is already a number.

But I'm closing this one as it is now. Using unconventional techniques for their side effects is not how to create a maintainable code base

**Pull request closed without merging**
