### PR TITLE
[Fix] Exclude not own properties when looping on options

### PR DESCRIPTION
**Pull request by JakeChampion**
It seems this was a regression as it was added before -- https://github.com/mochajs/mocha/pull/1586

### CODE REVIEW

**Comment by boneskull** [comment]
the chances of this breaking somebody's setup are probably greater than it actually addressing any problems.  if there's a bug here, we can revisit.  thanks though!

**Comment by JakeChampion** [comment]
It broke our setup on https://cdn.polyfill.io :-(

**Comment by boneskull** [comment]
@JakeChampion Where was the check added?  How did your setup break?

**Comment by triblondon** [comment]
@boneskull do you really think people are relying on setting mocha config options by extending the Object prototype?

**Pull request closed without merging**
