### PR TITLE
travis: use docker containers

### PR DESCRIPTION
**Pull request by parkr**
The docker containers are far more abundant and
offer vastly reduced boot time and some increased
CPU power. As long as you don't require 'sudo',
this is the way to go.

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by boneskull** [comment]
Cool idea.

**Comment by dasilvacontin** [comment]
Goes. :shipit:

**Comment by boneskull** [comment]
Unfortunately...this doesn't seem to be noticeably faster.

**Comment by parkr** [comment]
The boot time isn't recorded, but is much much shorter. Added CPU won't make a huge difference with already-fast tests.

**Comment by boneskull** [comment]
Well, I'll take your word for it.

**Pull request merged**
