### PR TITLE
#3128 replace phantomjs with puppeteer for browser tests

### PR DESCRIPTION
**Pull request by akrawchyk**
### Description of the Change

Replaces PhantomJS with Puppeteer and updates Karma to use `ChromeHeadless` browser.

### Alternate Designs

The issue https://github.com/mochajs/mocha/issues/3128 describes using `karma-headless-chrome-launcher` for this.

However, the project already has `karma-chrome-launcher` as a dependency, see https://github.com/mochajs/mocha/pull/3152#issuecomment-353445511. ~~which has documentation for setting up `ChromeHeadless`, see https://github.com/karma-runner/karma-chrome-launcher#headless-chromium-with-puppeteer. I thought this would be preferred, so I configured Karma to use Puppeteer.~~

~~Also, during my testing the `karma-headless-chrome-launcher` was unable to locate Chromium. I'm not sure it's supported [by the library used to locate Chrome](https://github.com/CliftonH/karma-headless-chrome-launcher/blob/master/index.js#L6) for that plugin, see https://github.com/hughsk/chrome-location/issues/7.~~

`karma-chrome-launcher` does not locate Chromium by default either. Both Travis and Appveyor use Google Chrome, but you can use Chromium to run tests locally by setting the `CHROME_BIN` env var:

```
CHROME_BIN=$(which chromium-browser) make test-browser
```

### Why should this be in core?

https://github.com/mochajs/mocha/issues/3128#issuecomment-350177398

### Benefits

https://github.com/mochajs/mocha/issues/3128#issuecomment-350177398

### Possible Drawbacks

~~Puppeteer downloads a usable Chrome binary on install. This download is currently >95MB in size compared to PhantomJS <20MB, almost 5x bigger download. This is undesirable for obvious reasons.~~

### CODE REVIEW

**Comment by akrawchyk** [comment]
Looks like [puppeteer requires Node >=v6](https://github.com/GoogleChrome/puppeteer#installation). If this is the desired path, it would have to wait on https://github.com/mochajs/mocha/issues/3149.

**Comment by akrawchyk** [comment]
@boneskull thanks for the feedback, I fixed the commit message.

> Unfortunately, there's no such thing as an "optional dev dependency". This would be nice since we don't actually need it, since we only run the browser tests from Node.js v8.x.

Agreed, but it is nice to be able to depend on puppeteer's binary instead of adding dependencies to resolve the paths to Chrome.

> Would downgrading to a version that supports Node.js v4.x work? Happy to hear other suggestions as well.

I looked through the commit history for the project and I don't think this is viable since the project makes heavy use of ES6 features (like destructuring and default function params) that are not supported on older versions of Node, unfortunately.

I'm going to follow [this guide](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai) and tinker some more with the Karma config to try and get this working without puppeteer as a dependency.

**Comment by akrawchyk** [comment]
@boneskull I removed puppeteer since `karma-chrome-launcher` appears to work out of the box (see thread at https://github.com/karma-runner/karma/issues/2489 as well as the guide I linked above).

I updated the Travis config based on https://docs.travis-ci.com/user/chrome but I don't think we need to do the additional setup for Chrome headless here since Karma takes care of launching Chrome.

The Appveyor config doesn't need to be updated since Chrome is included in the build worker images (see https://www.appveyor.com/docs/build-environment/#test-runners).

**Comment by akrawchyk** [comment]
@boneskull let me know your feedback once you get a chance to review the changes I pushed, thanks!

**Comment by boneskull** [comment]
thanks

**Comment by boneskull** [comment]
I'm going to pull this down and try it out; I'll address the conflict in `package-lock.json` as well.

**Comment by boneskull** [comment]
awesome.  merged via e54370eaa4b16db96f14157fdce06272e2b4ec68

thanks @akrawchyk

**Pull request closed without merging**
