### PR TITLE
fix: Cant scroll test results in debug mode.

### LINKED ISSUE #2463: Cant scroll test results in debug mode.
This issue seems to be happening for me on version 2.2.5 and even after upgrading to latest 3.0.2.

screen shot 2016-08-30 at 3 10 50 pm

### PR DESCRIPTION
**Pull request by kakadiya91**
While running tests in the debug mode, this fix will let you scroll right now if you have a lot of tests so that it ends up taking more vertical space on screen than your browsers viewport height.

fixes #2463

### CODE REVIEW

**Comment by palortoff** [comment]
Tests failing in this commit are fixed with #2468

**Comment by kakadiya91** [comment]
before:
c7787548-6ec4-11e6-9ea0-860c33a6b32f

after:
screen shot 2016-09-17 at 6 29 11 pm

**Comment by kakadiya91** [comment]
@boneskull we have added a work around in our code css so that it doesn't cause this issue anymore, not sure if we still need this change in mocha.

**Comment by boneskull** [comment]
@kakadiya91 Thanks!

**Comment by hollomancer** [comment]
I'll check this out.

**Comment by boneskull** [comment]
@hollomancer you may need some assistance to test this w/ Karma.  Let me know if I can help.  I'll target this for v3.1.0.

**Comment by boneskull** [comment]
closing this as I can't find any functional difference after the changes.  either way, I could scroll.  the presence of the scroll bar is determined (in macOS, at least) by the OS--might not be so with other systems. 

If someone needs this, please let me know.

**Pull request closed without merging**
