### PR TITLE
Added a reminder about the done() callback to test timeout error message

### PR DESCRIPTION
**Pull request by Soviut**

### CODE REVIEW

**Comment by dasilvacontin** [comment]
You are missing another error message at line 206.

**Comment by Soviut** [comment]
Woops. I've updated all the messages and pushed.

**Comment by dasilvacontin** [comment]
No problemo! Now you need to squash commits, though.

**Comment by Soviut** [comment]
Okay, here we go. Let's hope my sparse rebasing skills are up to it.

**Comment by dasilvacontin** [comment]
There are still two commits. If you'd like any help, I'm at mocha's gitter room.

**Comment by Soviut** [comment]
I've squashed them into a single commit now.

**Comment by dasilvacontin** [comment]
Oh, sorry, I thought you meant you already did it.

PR looks good now, thanks! :)

**Comment by Soviut** [comment]
Thanks. No, I was saying I'd be a while making sure I got the rebase working properly. The only time I ever really do it is in PRs so I don't have much practice.

**Comment by dasilvacontin** [comment]
Same here. Though I should do it more often, specially for commits that are just for saving work in progress.

**Pull request merged**
