### PR TITLE
chore: update chokidar to 3.6.0

### PR DESCRIPTION
**Pull request by orgads**
## Overview

Update chokidar to 3.6.0.

### CODE REVIEW

**Comment by voxpelli** [comment]
@orgads There are lots of outdated dependencies in this project, to help us prioritize, can you explain the reasoning for updating this specific one?

**Comment by JoshuaKGoldberg** [comment]
I think the not using `^` versions is the more curious point to investigate. Filed #5114.

Marking this one as draft pending discussion there.

Thanks for pointing this out!

**Comment by voxpelli** [comment]
> nest-cli updated to 3.6.0 (pinned), and it uses mocha.

@orgads And the benefit of updating here is that the `chokidar` in `nest-cli` and in `mocha` can be deduped by npm and thus you get fewer individual versions in your `node_modules`?

Or any more urgent issue?

**Comment by orgads** [comment]
It's been a month 😅

IIRC there was a Typescript compatibility issue too, but I'm unsure.

**Comment by voxpelli** [comment]
All dependencies will be updated in due time as we move further in our reboot of the project (https://github.com/mochajs/mocha/issues/5027) and eventually be done so with automated PR:s: https://github.com/mochajs/mocha/issues/5055

But if any dependency is causing urgent issues then it of course requires more urgent attention, hence my questions 🙂

**Comment by voxpelli** [comment]
Closing, we will update dependencies together with Mocha 11, #5216, no need for separate PR:s.

**Pull request closed without merging**
