### PR TITLE
Upgrade docdash version - issue #3663

### PR DESCRIPTION
**Pull request by tendonstrength**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

Upgrading the docdash library to ^2.0.0 per issue #3663 

### Alternate Designs

N/A

### Why should this be in core?

This is need to take advantage of functionality of newer docdash versions

### Benefits

Newer features in new docdash versions

### Possible Drawbacks

Possible dependency or document formatting issues. I spot checked generated docs and they seemed normal to me. 

### Applicable issues

Issue #3663

### CODE REVIEW

**Comment by outsideris** [comment]
@tendonstrength  Please sign CLA.

**Comment by tendonstrength** [comment]
@outsideris I thought I had signed it and when I go to the CLA site it says I have signed. Weird that the check is not working:

screen shot 2019-02-17 at 9 18 39 am

Is there something I'm missing?

**Comment by outsideris** [comment]
@tendonstrength It's weird. The CLA bot may have some problem temporarily.

**Comment by tendonstrength** [comment]
@outsideris I'm going to try closing and re-opening the PR to see if it gives it a kick in the pants.

**Comment by tendonstrength** [comment]
I opened an issue against the CLA assistant project. Not sure if they can help but we'll see what they say: https://github.com/cla-assistant/cla-assistant/issues/415

**Comment by tendonstrength** [comment]
@outsideris I fixed the CLA issue. Turns out the commit had my work email address which didn't match my GitHub address. Please let me know if there's anything else, and thanks for taking a look at this.

**Comment by boneskull** [comment]
I'll go ahead and resolve the conflicts and merge here.

**Comment by boneskull** [comment]
lgtm, thanks

**Pull request merged**
