### PR TITLE
closes #3702 default column CSS

### LINKED ISSUE #3702: 🛠️ Repo: Two-column lists in the docs should not be the default style for lists
This should not be the default list style:

image

Change the stylesheet to display a "normal" list unless we apply a specific class for two-column display.  I think it's OK to use in some places, but not for *all* lists.

unless there's a way to specify the class in our markdown compiler (not sure), just use html for the ones we keep.  features and table of contents are good to keep... not sure about the rest.

For implementors:

To see changes locally, run `npm start docs` and open up `docs/_dist/index.html` with your browser. You can also do `npm start docs.watch` to rebuild as you work (you'll still have to reload).

### PR DESCRIPTION
**Pull request by crossaaron**
### Description of the Change
Changed default CSS for `<ul>` elements to single column.
Created a "two-column-display" class as well for use if desired.

### Alternate Designs
NA

### Why should this be in core?
NA (already exists)

### Benefits
Requested styling fix

### Possible Drawbacks
Longer scroll down

### Notes
Had to reinstall "wd" module to get tests to run completely and without error locally

### Applicable issues
Fixes #3702 
semver-patch

### CODE REVIEW

**Comment by crossaaron** [comment]
I guess I'm a little stumped on how that would work as it shows up in the
deploy preview as desired,  but the deployed actual applies the 2 column
format.  Are you looking to nest the automatically generated content within
the ToC?

**Comment by plroebuck** [comment]
Append your class after last list item in "Features" 
#### "/docs/index.md"
```md
- [TextMate bundle](#textmate)
{:class="two-column-display"}
```

**Comment by plroebuck** [comment]
Two ways to do the TOC. See if @boneskull has preference...
**Pick one or the other.**

* Modify **"/scripts/markdown-magic.config.js"**, adding the class to TOC.
```js
  toc: (content, options, config) => {
    const IGNORED_HEADINGS_REGEXP = /Features|Table of Contents/i;
    const toc = markdownToc(config.outputContent, {
      slugify: require('uslug'),
      bullets: options.bullets,
      firsth1: false,
      // if filter is supplied, maxdepth is apparently ignored,
      // so we have to do it ourselves.
      filter: (str, ele) => ele.lvl < 2 && !IGNORED_HEADINGS_REGEXP.test(str)
    }).content;
    return '\n' + toc + '\n' + '{:class="two-column-display"}' + '\n';
  },
```
* Modify **"/docs/css/style.css"**, adding CSS selector for TOC to existing "two column" definition
```css
h2#table-of-contents + ul,
ul.two-column-display {
  column-gap: 30px;
  column-count: 2;
}
```

**Comment by plroebuck** [comment]
@boneskull,
Would like to get this done. Please state any implementation preference you have...

**Comment by craigtaub** [comment]
2nd option seems fine IMO, @boneskull sound ok to you?
@crossaaron are you able to fix this please?

**Pull request closed without merging**
