### PR TITLE
[JSHint] lib/mocha.js with less errors contributes to #1359

### PR DESCRIPTION
**Pull request by ainthek**
I gave up to fix this in one round,
I will post incremental fixes, If you accept each and we will,end up with clean "own sources" 
then we can automate the process and set up the rules, before then, it would be the show stopper.

So PLEASE accept partial, pull requests, and one day we may get cleaner code base.

Thanx

### CODE REVIEW

**Comment by travisjeffery** [comment]
Thanks, but personally don't like some of the config here. will add something to fix this shortly.

**Comment by danielstjules** [comment]
Closing for now as the PR has been inactive for almost a month, and Travis expressed an interest in enforcing different conventions. Appreciate your work on this though! I'm sure the team is in agreement that it would be nice to converge on an accepted style throughout the codebase, and for future work. :)

**Comment by boneskull** [comment]
Fwiw most if not all of the code changes look fine to me

**Comment by danielstjules** [comment]
The second change stuck out:
``` javascript
-  if (arguments.length === 0) return this.runnable().timeout();
+  if (! arguments.length ) return this.runnable().timeout();
```

Adding a space before the closing brace of that conditional expression. As well as after the logical not. I personally like:

``` javascript
-  if (arguments.length === 0) return this.runnable().timeout();
+  if (!arguments.length) return this.runnable().timeout();
```

Though you may want to keep spaces after not operators. But that's totally up to @travisjeffery and yourself, as owners/maintainers of the project. :)

If you feel like the changes are fine, we can def reopen this. Would just take some rebasing, as there's a few conflicts. E.g. https://github.com/mochajs/mocha/pull/1555/files#diff-aa849a970cef551664c12f04a4209f6fL167, and https://github.com/mochajs/mocha/pull/1555/files#diff-037110b12e45b56f6f5c48b9cf213ab6R226 which was added in https://github.com/mochajs/mocha/commit/00ef54cd41d46b1c29358942dc0874e2ae7da0ff#diff-037110b12e45b56f6f5c48b9cf213ab6L226

Otherwise, another solution would be to open a PR that discusses/establishes the .jshintrc configuration we'd like to use.

**Pull request closed without merging**
