### PR TITLE
Upgrade yargs-parser dependency to avoid loading 2 copies of yargs

### PR DESCRIPTION
**Pull request by cspotcode**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### CODE REVIEW

**Comment by cspotcode** [comment]
As far as I know, `yargs` does not expose a reference to `yargs-parser`, so if we want to use it directly -- which mocha does -- then we need to declare a dependency on it.

It might make sense for `yargs` to re-export the parser as part of its public API, to simplify these situations.

**Comment by boneskull** [comment]
@plroebuck 	Yeah, that's the reason.  We don't need to "go full yargs" when people use `bin/mocha`, since `bin/_mocha` does.  We _do_ need to parse the arguments (hopefully as little as possible) in order to determine what we do with Node.js flags and tell `bin/_mocha` not to bother with config files.

**Comment by plroebuck** [comment]
So this will be a recurring issue... unless there's a change so that `yargs` re-exports the parser as part of its public API?

**Comment by cspotcode** [comment]
The issue will only recur if a mocha developer changes the yargs or yargs-parser dependency without bumping the other to match.

**Pull request merged**
