### PR TITLE
Adds BigInt support to stringify util function.

### LINKED ISSUE #4090: Bigint support.
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description
`bigint` is now a Stage 4 proposal but if you assert on a `bigint` Mocha fails during serialization of the error.  I don't know how to reproduce this issue without `Chai`, but the error context _suggests_ that the problem is with Mocha's error serializer, not Chai.

### Steps to Reproduce
```javascript
const expect =  require('chai').expect

describe('test', () => {
	it('test', async () => {
		expect(1n).equals(0n)
	})
})
```

**Expected behavior:** [What you expect to happen]
Chai doesn't natively support `bigint` either (separate issue), but it at least doesn't error on reporting.  For now, I would expect to see Chai's worthless error message that at least pointed to the right test/line.

**Actual behavior:** [What actually happens]
```
  test
(node:14544) UnhandledPromiseRejectionWarning: TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at _stringify (C:\Users\micah\Source\test\node_modules\mocha\lib\utils.js:409:20)
    at jsonStringify (C:\Users\micah\Source\test\node_modules\mocha\lib\utils.js:360:12)
    at Object.exports.stringify (C:\Users\micah\Source\test\node_modules\mocha\lib\utils.js:332:14)
    at stringifyDiffObjs (C:\Users\micah\Source\test\node_modules\mocha\lib\reporters\base.js:168:24)
    at Runner.<anonymous> (C:\Users\micah\Source\test\node_modules\mocha\lib\reporters\base.js:309:7)
    at Runner.emit (events.js:205:15)
    at Runner.fail (C:\Users\micah\Source\test\node_modules\mocha\lib\runner.js:304:8)
    at C:\Users\micah\Source\test\node_modules\mocha\lib\runner.js:673:18
    at done (C:\Users\micah\Source\test\node_modules\mocha\lib\runnable.js:334:5)
    at C:\Users\micah\Source\test\node_modules\mocha\lib\runnable.js:398:11
(node:14544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 6.2.2
- The output of `node --version`: v12.3.0
- Your operating system
  - name and version: Windows 10
  - architecture (32 or 64-bit): 64-bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): pwsh
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): Chai 4.2.0
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): No.

### PR DESCRIPTION
**Pull request by JosejeSinohui**
### Description of the Change
Fixes #4090, adds a new case to the _stringify function in utils so it can handle the BigInt case.

### Alternate Designs
There were two choices considered in the issue `BigInt<123>` or `123n` i went with the latter because it's the standard way JS presents BigInts

### Why should this be in core?
Nice way of representing BigInts in errors.

### Benefits

Support for Stringify-ing BigInts
### Possible Drawbacks
I had to add `/* global BigInt */` at the top of the spec file, i don't know if that is the best place for it.

### Applicable issues
Fixes #4090

### CODE REVIEW

**Comment by JosejeSinohui** [comment]
I already signed the Contributor License Agreement, i don't know why does it show like pending, is there a way to reset it to sign it again?

**Comment by boneskull** [comment]
it could be a mismatch between username / email address. 

some ideas:

- is the email the same in the commits?
- is the email address and username in the CLA tool the same as your github account?
- does email address on github account match the email address you used in the tool?

**Comment by boneskull** [comment]
the test should be failing in IE11 and maybe safari... hmm.

**Comment by JosejeSinohui** [comment]
> the test should be failing in IE11 and maybe safari... hmm.

i checked compatibility here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

is there something i am missing?

**Comment by JosejeSinohui** [comment]
@boneskull any follow up on this?

**Comment by boneskull** [comment]
just that those don’t support BigInt but I’m confused about why they weren’t failing CI. could you look in to it? I don’t have time atm. hoping to have more time for project after new year

**Comment by JosejeSinohui** [comment]
From what i see, the CI runs tests only on different NodeJs versions, Node 8 doesn't support BigInts either but I only added a new case to the stringify function, in that case it uses the toString function to create the representation of the BigInt, so the code it's never instantiating a BigInteger, just knows how to handle one if it ever receives it.
The build was failing before because in the test that I added was creating a BigInt to test that it was correctly parsed into a string with the stringify function. Because of this the test didn't pass in node8 because BigInteger wasn't supported there. To fix it I just added a check for support before trying it.

**Comment by mvlabat** [comment]
Mocha just hangs for me when it tries to assert equality of two different bigints (it's fine when they are equal though). Might it be related to the issue that this PR fixes?

@boneskull any chance this PR gets merged anytime soon? Sorry to nudge.

**Comment by mattbishop** [comment]
👍 BigInt support is widespread in 2021: https://caniuse.com/?search=bigint

**Comment by juergba** [comment]
I rebased to `master` branch.
I don't know why the ESLint test is failing, I will have a look later.
The cancelled browser test (pull_request) is off-topic, due to our GH actions setup.

**Comment by juergba** [comment]
GH actions has problems with downloading an artifact and therefore the ESLint tests fail. It doesn't seem to be related to this PR.
I restarted our CI tests on another, successfully passing PR and the ESLint tests fail now.
It's not the first time GH actions is behaving weirdly.

**Review by juergba — APPROVED** [review]
@JosejeSinohui thank you. I apologize for the long delay.

**Pull request merged**
