### PR TITLE
[JSHint] Unnecessary semicolons fixed in source files and regenerated mo...

### PR DESCRIPTION
**Pull request by ainthek**
...cha.js

Hopefully fixing sources, not product of Make this time

I have fixed /lib and compile.js and
regenerated mocha.js:

	make clean
	make
	jshint mocha.js | grep Unnecessary

No more Unnecessary semicolons errors shall result from last grep

### CODE REVIEW

**Comment by boneskull** [comment]
thanks.  please squash and we'll merge

**Comment by ainthek** [comment]
Please boneskull, squash yourself if you find them related and want one commit, it is much less work for you then for me.... (jesus, I love this style of work....).

**Comment by ainthek** [comment]
original PR has only the first commit, the other 2, is just too intelligent github

**Comment by boneskull** [comment]
@ainthek To help in the future, you may wish to Google a few articles about PR etiquette and why projects want them to be squashed. It's not necessary to close PRs and open new ones to do this, if that's what you're thinking. 

I'd like to merge your code, but we need to cooperate. Thanks for your contribution!

**Pull request closed without merging**
