### PR TITLE
test: fix npm scripts on windows

### LINKED ISSUE #5220: 🛠 Repo: Windows fails to run `npm test`
### Tooling Suggestion Checklist

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have pulled the latest `main` branch of the repository.
- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I want to provide a PR to resolve this

### Overview

When installing on Windows, `npm test` gives the following error:

```
~/repos/mocha (main)
$ npm test

> mocha@10.7.3 test
> run-s lint test-node test-browser

... cut for GitHub ...

> mocha@10.7.3 lint:markdown
> markdownlint '*.md' 'docs/**/*.md' '.github/*.md' 'lib/**/*.md' 'test/**/*.md' 'example/**/*.md' -i CHANGELOG.md

Usage: markdownlint [options] <files|directories|globs>

MarkdownLint Command Line Interface

Options:
  -V, --version                               output the version number
... cut for GitHub ...
  -h, --help                                  display help for command

Oops! Something went wrong! :(

ESLint: 8.56.0

No files matching the pattern "'bin/*'" were found.
Please check for typing mistakes in the pattern.

ERROR: "lint:code" exited with 2.
ERROR: "lint" exited with 1.
```

This is because of the single quotes. Removing them resolves the issue, but it's unclear if that affects other OS-es

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by mark-wiemer**
Closes #5220

Single quotes weren't resolved correctly on Windows. The single quotes don't seem necessary on any OS as they were never wrapping a space character.

Knip also reported prettier as unused, so I've added prettier to Knip's ignore list.

`npm test` is now passing on a clean install from on Windows, where it was failing before.

Ref https://github.com/mark-wiemer/mocha/pull/1 for status checks

### CODE REVIEW

**Comment by voxpelli** [comment]
This is a bit unintuitive to me – my impression is that the quotes should be there so that the js-based glob resolves rather than the shell glob 🤔

**Comment by mark-wiemer** [comment]
@voxpelli I'm not a glob expert, in my book if it works it works, but obviously if you don't feel comfortable merging that's fine. I'll dig deeper as obviously the tests are now failing on other operation systems

**Comment by mark-wiemer** [comment]
2 checks failed image

Investigating remaining issues now, ref https://github.com/mark-wiemer/mocha/pull/1:

- https://github.com/mark-wiemer/mocha/actions/runs/11094433059/job/30821980668?pr=1
- https://github.com/mark-wiemer/mocha/actions/runs/11094433059/job/30821980743?pr=1

**Comment by mark-wiemer** [comment]
I'm able to reproduce this issue locally with Node 22 on Windows, looks like the same err message. Going to see if different versions of 22.x work:

<details><summary>Full output</summary>

```
~/repos/mocha (mark-wiemer/lint)
$ fnm use 22
2024-09-29 10:35:59
Using Node v22.9.0
[last: 0s]
~/repos/mocha (mark-wiemer/lint)
$ npm run test-node:integration
2024-09-29 10:36:06

> mocha@10.7.3 test-node:integration
> run-s clean build && npm run -s test-node-run -- --parallel --timeout 10000 --slow 3750 "test/integration/plugins/root-hooks.spec.js"


> mocha@10.7.3 clean
> rimraf mocha.js mocha.js.map


> mocha@10.7.3 build
> rollup -c ./rollup.config.js


./browser-entry.js → ./mocha.js...
created ./mocha.js in 1.9s


  root hooks
    when mocha run in serial mode
      ✔ should run root hooks when provided via mochaHooks object export
      ✔ should run root hooks when provided via mochaHooks function export
      support ESM when type=module or .mjs extension
        ✔ should run root hooks when provided via mochaHooks
      support ESM via .js extension w/o type=module
        1) should fail due to ambiguous file type
    when mocha in parallel mode
      ✔ should run root hooks when provided via mochaHooks object exports
      ✔ should run root hooks when provided via mochaHooks function export
      when running multiple jobs
        ✔ should run root hooks when provided via mochaHooks object exports for each job


  6 passing (9s)
  1 failing

  1) root hooks
       when mocha run in serial mode
         support ESM via .js extension w/o type=module
           should fail due to ambiguous file type:
     
expected Promise when fulfilled to contain output /SyntaxError: Unexpected token/
  expected
  {
    output: '\n✖ \x1b[31mERROR:\x1b[39m Error [ERR_REQUIRE_CYCLE_MODULE]: Cannot require() ES Module C:\\Users\\markw\\repos\\mocha\\test\\integration\\fixtures\\plugins\\root-hooks\\root-hook-defs-esm-broken.fixture.js in a cycle.\n    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:303:15)\n    at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)\n    at Module._compile (node:internal/modules/cjs/loader:1503:5)\n    at Module.replacementCompile (C:\\Users\\markw\\repos\\mocha\\node_modules\\append-transform\\index.js:60:13)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)\n    at Object.<anonymous> (C:\\Users\\markw\\repos\\mocha\\node_modules\\append-transform\\index.js:64:4)\n    at Module.load (node:internal/modules/cjs/loader:1317:32)\n    at Module._load (node:internal/modules/cjs/loader:1127:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)\n    at cjsLoader (node:internal/modules/esm/translators:329:5)\n    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:260:7)\n    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)\n    at async formattedImport (C:\\Users\\markw\\repos\\mocha\\lib\\nodejs\\esm-utils.js:2:567)\n    at async exports.requireOrImport (C:\\Users\\markw\\repos\\mocha\\lib\\nodejs\\esm-utils.js:7:1135)\n    at async exports.handleRequires (C:\\Users\\markw\\repos\\mocha\\lib\\cli\\run-helpers.js:38:364)\n    at async C:\\Users\\markw\\repos\\mocha\\lib\\cli\\run.js:18:40 {\n  code: \'ERR_REQUIRE_CYCLE_MODULE\'\n}\n',
    code: 1,
    args: [
      'C:\\Users\\markw\\repos\\mocha\\bin\\mocha.js',
      '--require=C:\\Users\\markw\\repos\\mocha\\test\\integration\\fixtures\\plugins\\root-hooks\\root-hook-defs-esm-broken.fixture.js',
      '--no-color',
      '--no-bail',
      '--no-parallel'
    ],
    command: 'C:\\Users\\markw\\repos\\mocha\\bin\\mocha.js --require=C:\\Users\\markw\\repos\\mocha\\test\\integration\\fixtures\\plugins\\root-hooks\\root-hook-defs-esm-broken.fixture.js --no-color --no-bail --no-parallel'
  }
  to contain output /SyntaxError: Unexpected token/


  expected Promise when fulfilled to contain output /SyntaxError: Unexpected token/
    expected
    {
      output: '\n✖ \x1b[31mERROR:\x1b[39m Error [ERR_REQUIRE_CYCLE_MODULE]: Cannot require() ES Module C:\\Users\\markw\\repos\\mocha\\test\\integration\\fixtures\\plugins\\root-hooks\\root-hook-defs-esm-broken.fixture.js in a cycle.\n    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:303:15)\n    at loadESMFromCJS (node:internal/modules/cjs/loader:1381:24)\n    at Module._compile (node:internal/modules/cjs/loader:1503:5)\n    at Module.replacementCompile (C:\\Users\\markw\\repos\\mocha\\node_modules\\append-transform\\index.js:60:13)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)\n    at Object.<anonymous> (C:\\Users\\markw\\repos\\mocha\\node_modules\\append-transform\\index.js:64:4)\n    at Module.load (node:internal/modules/cjs/loader:1317:32)\n    at Module._load (node:internal/modules/cjs/loader:1127:12)\n    at TracingChannel.traceSync (node:diagnostics_channel:315:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)\n    at cjsLoader (node:internal/modules/esm/translators:329:5)\n    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:260:7)\n    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)\n    at async formattedImport (C:\\Users\\markw\\repos\\mocha\\lib\\nodejs\\esm-utils.js:2:567)\n    at async exports.requireOrImport (C:\\Users\\markw\\repos\\mocha\\lib\\nodejs\\esm-utils.js:7:1135)\n    at async exports.handleRequires (C:\\Users\\markw\\repos\\mocha\\lib\\cli\\run-helpers.js:38:364)\n    at async C:\\Users\\markw\\repos\\mocha\\lib\\cli\\run.js:18:40 {\n  code: \'ERR_REQUIRE_CYCLE_MODULE\'\n}\n',
      code: 1,
      args: [
        '--require=C:\\Users\\markw\\repos\\mocha\\test\\integration\\fixtures\\plugins\\root-hooks\\root-hook-defs-esm-broken.fixture.js',
        '--no-color',
        '--no-bail',
        '--no-parallel'
      ],
    }
    to contain output /SyntaxError: Unexpected token/
      at Array.forEach (<anonymous>)
  From previous event:
      at Context.<anonymous> (test\integration\plugins\root-hooks.spec.js:140:16)
      at callFn (lib\runnable.js:110:584)
      at Runnable.run (lib\runnable.js:110:57)
      at Runner.runTest (lib\runner.js:182:1054)
      at C:\Users\markw\repos\mocha\lib\runner.js:210:654
      at next (lib\runner.js:159:422)
      at C:\Users\markw\repos\mocha\lib\runner.js:159:809
      at next (lib\runner.js:147:579)
      at Immediate.<anonymous> (lib\runner.js:151:1253)
      at process.processImmediate (node:internal/timers:491:21)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace



[last: 27s]
```
</summary>

**Comment by mark-wiemer** [comment]
- Last good node: 22.6.0
- First bad node: [22.7.0](https://github.com/nodejs/node/releases/tag/v22.7.0)

**Comment by mark-wiemer** [comment]
Added tests to distinguish between `--no-experimental-module-detection` and `--experimental-module-detection` as the latter is the default in Node 22.7 and later

**Review by voxpelli — APPROVED** [review]
Looks good to me! Thanks 🙏 

Extra thanks for fixing the tests for latest Node version!

**Comment by jorenbroekema** [comment]
Might have been nice to add this as a breaking change in the CHANGELOG.

Upgrading my mocha version to after this PR was merged and released, it introduced the problem that on Windows the following:

```sh
mocha -r mocha-hooks.mjs './*.test.js'
```
Produces output: 
```
Error: No test files found: "'./*.test.js'"
```
Whereas this was working fine before.

**Comment by mark-wiemer** [comment]
@jorenbroekema please open a new issue, I don't understand how changes to our internal test files and package.json could cause this, if you provide a more detailed repro in the new issue I'm happy to review :)

**Pull request merged**
