### PR TITLE
expand / update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by boneskull**
This text is a first pass at what should eventually appear on the site.  Eventually, I'd like this file to be simply links to the site.  It should be expanded and organized further.

[View it](https://github.com/boneskull/mocha/blob/6c820bc6cfb5f6940bc27be3b80a0d2f3749101b/CONTRIBUTING.md)

### CODE REVIEW

**Comment by boneskull** [comment]
RFC! @mochajs/core

**Comment by boneskull** [comment]
@mikesherov this is what I'd like to use for now.  The PR in [the site repo](/mochajs/mochajs.github.io) contains much of this, but the site needs some other things addressed before it makes sense to add another page.

**Comment by boneskull** [comment]
I'm not sure why this PR was created from my fork, but oh well.

**Comment by mikesherov** [comment]
👍

**Comment by dasilvacontin** [comment]
We can iterate later if necessary; this is a great improvement already :). 👍

**Pull request merged**
