### PR TITLE
feature(mocha/grep): improve grep - issue #808

### PR DESCRIPTION
**Pull request by a8m**
Add the ability to pass `grep` as a regexp-like string. (query in the browser or flag in the cli).
This improvement gives you pass a regexp that including flags, and solved #808 as well.

e.g: 
```sh
$ mocha test/ --grep /^Suite/i
```

### CODE REVIEW

**Comment by danielstjules** [comment]
LGTM! :)

Some might argue that it breaks BC, and would require a major bump. e.g.:
``` javascript
it('/test/i', function() {});
it('test', function() {});
```
with something like `mocha --grep /test/i test.js`. Before this PR, you'll run one spec. After, you'll run two. But it's certainly an edge case, as with most BC discussions.

**Comment by dasilvacontin** [comment]
I couldn't take a look at it yet.

Def break BC, but since we have other changes that do so too we can just ship them together in the next major.

**Comment by boneskull** [comment]
@a8m possible to rebase against branch `v3.0.0`?

**Comment by a8m** [comment]
Sure, l'II do it later.
same with #1634, #1591

thx

**Comment by a8m** [comment]
Rebased. but it seems to be causing an error on Travis.
Is there anyone who understand what the problem in [this build](https://travis-ci.org/mochajs/mocha/builds/59005927)?
/cc @mochajs/mocha

**Comment by dasilvacontin** [comment]
old npm version carret issue

**Comment by jbnicolai** [comment]
Yep, not an actual issue.

@a8m great feature! Let's merge and ship asap :)

**Comment by boneskull** [comment]
@a8m this still needs to be rebased... not sure what's happening here.

**Comment by a8m** [comment]
Replaced with #1808(rebased on top of v3.0.0)

**Pull request closed without merging**
