### PR TITLE
Update lodash.create

### PR DESCRIPTION
**Pull request by bdsomer**
As you can see through [this visualization](http://npm.anvaka.com/#/view/2d/mocha), updating [`lodash.create`](https://npmjs.com/package/lodash.create) would drastically reduce the number of dependencies that [`mocha`](https://npmjs.com/package/mocha) has, causing **faster install times** and occupying **less disk space**.

### CODE REVIEW

**Comment by ScottFreeCode** [comment]
Thanks for the PR! This sounds really helpful; I was looking for ways to cut down on install time not too long ago.

To be sure the new version works in all the environments Mocha supports, I think we'll want to rebase this after we [get the JWT stuff for SauceLabs set up](/mochajs/mocha/issues/2602) so that the Travis jobs are actually testing all the browsers (whereas right now there's a separate job for each browser but for PRs from forks they redundantly test PhantomJS instead).

**Comment by bdsomer** [comment]
@ScottFreeCode Okay, sounds good!

**Comment by boneskull** [comment]
See #2979; `lodash.create` *may* be able to be dropped when that happens.

**Comment by boneskull** [comment]
linking this to #3018.

**Comment by boneskull** [comment]
ok, we don't need this.  thanks anyhow!

**Comment by bdsomer** [comment]
@boneskull Sounds good!

**Pull request closed without merging**
