### PR TITLE
3363: Throw error if unable to parse Mocha options file

### LINKED ISSUE #2576: Should not silently fail given --opts option
We had a problem where mocha wasn't finding `mocha.opts`, but it was silently just letting it fly and trying to run the tests. If I specify with `--opts`, I would expect it to throw an error if the file doesn't exist:

```
mocha --opts foo.opts # should throw an error if foo.opts doesn't exist
```

### LINKED ISSUE #3363: Throw error if unable to parse Mocha options file
### Description

The current code silently ignores any problems parsing the options file and continues on.

https://github.com/mochajs/mocha/blob/99c2f8aa7bf4184fdf694887ef740f31fe29f1f2/bin/options.js#L32-L47

Code should instead throw an error for any error encountered, except for a nonexistent default options file (i.e., user did not specify `--opts` and "test/mocha.opts" does not exist).

### Downside?

People who have errors in their "mocha.opts" file will experience failures until corrected.

### PR DESCRIPTION
**Pull request by plroebuck**
### Description of the Change

Code now throws an error for any problems loading the Mocha options file (except for nonexistent default "test/mocha.opts").

Builds off of previous discussions and work done in PR #2716 and PR #3352 .

### Why should this be in core?

Silently ignoring problems loading this file is just wrong.

### Benefits

Users will now be told if the file failed to load.

### Possible Drawbacks

Users with invalid Mocha options files (or permissions problems, etc.) will need to correct the problem.

### Applicable issues

Fixes #3363
Fixes #2576 
(server-major) [since Mocha could throw an error when it didn't previously]

### CODE REVIEW

**Comment by plroebuck** [comment]
BTW, anyone run across [this ChromeHeadless problem](https://travis-ci.org/plroebuck/mocha/jobs/375058670) before? Same code ran file for all test jobs __except__ this last one. Restarting made no difference. MochaJS PR run afterwards was fine.

**Comment by outsideris** [comment]
@plroebuck You didn't set saucelab in your travisci, see`Please set SAUCE_USERNAME and SAUCE_ACCESS_KEY env variables`.

**Comment by plroebuck** [comment]
@outsideris, add "server-major" tag, pls!

**Comment by boneskull** [comment]
will review some stuff tomorrow

**Comment by outsideris** [comment]
@Bamieh I think this is a breaking change because users will get the errors when there is no opts file. Before this change, users don't care about the existence of the opts file.

**Comment by Bamieh** [comment]
@outsideris makes sense, but looking at the code, it will only throw if there is an error in the existing file. if it does *not* exist, no errors will be throws. So i have a feeling that this is more of a bug fix rather than a breaking change.


- Users with no opt file will not be affected.
- Users with working opt files will not be affected.
- Users with broken opt files will have a new exception thrown that did not throw in the past.

Do you think there are people running mocha with a broken opt file? I believe its not that case because mocha would not be running as they expect anyways.

**Comment by plroebuck** [comment]
Not exactly, @outsideris... It's a breaking change because an Error _could_ now occur where it does not in the current version. Even though the existing code is broken (due to masking), I consider it major since it _might_ disrupt the CI process by causing run failures.

Mocha now throws when user-specified `--opt` options file doesn't exist, cannot be read, or if a parsing error occurs due to its content; the default "test/mocha.opts" not existing will *not* trigger an error.

**Comment by plroebuck** [comment]
| Do you think there are people running mocha with a broken opt file? I believe its not that case
| because mocha would not be running as they expect anyways.

Point being that they may not even know it's broken yet...
 #2576

**Comment by plroebuck** [comment]
it's server-major if upgrading _can_ break something.
<https://blog.greenkeeper.io/introduction-to-semver-d272990c44f2>

**Comment by boneskull** [comment]
This would be a bug if Mocha had *intended* to throw an error upon an invalid opts file, but failed to do so correctly.  

Since Mocha's current behavior is intended (which is to say, *nothing*) this isn't a bug fix.  But it *is* a breaking change.

**Comment by plroebuck** [comment]
Had problems getting this branch updated post-UnexpectedJS. Opening new PR instead.

**Pull request closed without merging**
