### PR TITLE
Fix: reporters with chalk functions (fixes #2073)

### LINKED ISSUE #2073: -c option broken in 2.4.1
`-c` CLI option is broken in `2.4.1` but works in `2.3.4`.

**Scenario 1**
If I run mocha with `-c` flag then it doesnt even run my tests.
```sh
./node_modules/mocha/bin/_mocha -R progress -c tests/*.js
```

**Scenario 2**
If I run mocha without `-c` flag then it does run my tests but there is no color.
```sh
./node_modules/mocha/bin/_mocha -R progress tests/*.js
```

### PR DESCRIPTION
**Pull request by gyandeeps**
[Review on Reviewable](https://reviewable.io/reviews/mochajs/mocha/2074)

### CODE REVIEW

**Comment by boneskull** [comment]
looks good, thank you.

**Comment by boneskull** [comment]
(just waiting on travis)

**Comment by gyandeeps** [comment]
np :+1: 
Can we have a patch release plz?

**Comment by boneskull** [comment]
yes

**Comment by gyandeeps** [comment]
Thanks :smile:

**Pull request merged**
