### PR TITLE
Add documentation for filtering (grep, invert, tags, skipTags)

### PR DESCRIPTION
**Pull request by rprieto**
Documents the new `--tags` and `--skip-tags` options from pull request #1445.

### CODE REVIEW

**Comment by rprieto** [comment]
Happy new year! I'm keen to revive this PR, see what everyone thinks
(either the simple `--tags a,b,c` version, or the slightly more complex but more powerful `--tags a+b,c+d` version)

**Comment by rprieto** [comment]
Fair enough, we can probably revisit this when required. Does this mean any activity on #1445? :)

**Comment by jbnicolai** [comment]
Ah, no @rprieto - sorry for the confusion. GH closed this PR as it was directed at the now moved mochajs/mocha#gh-pages branch, which now resides under mochajs/mochajs.github.io#master.

I'll tag this for follow-up, and move it over to the new repo as soon as possible.

**Comment by jbnicolai** [comment]
And in response to your other question: #1445 is definitely still on my radar. We've been cutting our way through the long-lived PRs for a few days now, and we're down to 17 right now (from 35+ a few days back). So we'll get there :)

**Comment by rprieto** [comment]
Haha right, no problem then :) Nice work on the PRs!

**Pull request closed without merging**
