### PR TITLE
fix(vulnerability): update yargs-unparser to v1.6.1

### PR DESCRIPTION
**Pull request by martinoppitz**
### Requirements

See https://github.com/mochajs/mocha/issues/4332 and #4340.

The problem is a vulnerability in `lodash`. See here https://snyk.io/test/npm/mocha/

With this PR we fixed the second vulnerability. The first one was already fixed with PR https://github.com/mochajs/mocha/pull/4333.

### Description of the Change

Update `yargs-unparser` to v1.6.1.
Before: https://snyk.io/test/npm/yargs-unparser/1.6.0
After: https://snyk.io/test/npm/yargs-unparser/1.6.1

### CODE REVIEW

**Comment by martinoppitz** [comment]
Hello @juergba ,
I dont know, whats going wrong -- netlify/mocha/deploy-preview

Can you help me?

Thank you.

**Comment by boneskull** [comment]
1. revert `CHANGELOG.md`
1. rebase onto `master`

**Comment by martinoppitz** [comment]
@boneskull Done.

**Comment by martinoppitz** [comment]
How we can replay the PR checke?

**Pull request closed without merging**
