### PR TITLE
introduce package-lock.json; closes #3025

### LINKED ISSUE #3025: allow package-lock.json
mainly for performance reasons.  this will allow for better caching in CI, among other things.

### PR DESCRIPTION
**Pull request by boneskull**
- update `.travis.yml` to use npm@5 caching where available
- remove `.npmrc` (now unused)
- remove `package-lock.json` from `.gitignore`

### CODE REVIEW

**Comment by boneskull** [comment]
we'll deal w/ this later.

**Comment by brutalcrozt** [comment]
ping @boneskull, since you notify that you are back now. :smile:

**Comment by boneskull** [comment]
@brutalcrozt do you need this for something?

**Comment by brutalcrozt** [comment]
No at all, it's seem simple. Just hoping number of open PR, and issue got decreased.

**Pull request merged**
