### PR TITLE
Fix an error when fn===undefined

### PR DESCRIPTION
**Pull request by Lana-Light**
This change fixes an error that occurs when reporter is 'xunit' and run is called without callback: " /rbd/pnpm-volume/a49b9a7c-c3f0-42ba-ae66-612ead86e96c/node_modules/.registry.npmjs.org/mocha/5.2.0/node_modules/mocha/lib/reporters/xunit.js:126
 fn(failures);  ^
TypeError: fn is not a function "

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### CODE REVIEW

**Comment by Lana-Light** [comment]
Hi! Here is link to the project, where this bug occurs. Also there is function run2, which fixes the bug. [https://glitch.com/edit/#!/test-function-run?path=server.js:17:0](https://glitch.com/edit/#!/test-function-run?path=server.js:17:0) . When I use `mocha.ui('tdd').reporter('xunit').run(function() {});` or `mocha.run2 = run2; mocha.ui('tdd').reporter('xunit').run2();` it works, but if `mocha.ui('tdd').reporter('xunit').run();` it throws an error. This code ```if (reporter.done) {
      reporter.done(failures, fn);
    }``` attemts to call fn even if it is `undefined` and cause this error in console 
image

**Comment by boneskull** [comment]
The line you've changed isn't the problematic line in your screenshot...

**Comment by boneskull** [comment]
OK, I understand. Can you please add a test for this?

**Comment by Lana-Light** [comment]
I have added a test #3620 .

**Comment by boneskull** [comment]
@Lana-Light The [lint check is failing](https://travis-ci.org/mochajs/mocha/jobs/469515071#L497).  Did you happen to make these changes directly on GitHub?  

After cloning the repo and running `npm install`, when you commit, your code will automatically be formatted to avoid this problem.

See the [step-by-step guide](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md#shoe-contributing-code-step-by-step) for more info.

**Comment by boneskull** [comment]
@Lana-Light Yes.  It's best practice to do this, as most projects (including this one) ask that you run tests on your changes *before* sending a PR.  Additionally, Mocha has tooling which will automatically format your code correctly upon commit, which is not invoked when committing on GitHub.

Making changes on GitHub directly should rarely be used for anything other than documentation updates.

**Comment by boneskull** [comment]
LGTM, thanks!

**Pull request merged**
