### PR TITLE
trigger netlify deploy nightly

### PR DESCRIPTION
**Pull request by boneskull**
This sets up a job to run at 00:00 UTC every day, which rebuilds the site from the `mochajs.org` branch.  This keeps the list of supporters up-to-date.  It relies on a secret env var to do its thing.

Will try to figure out how to test this...

### CODE REVIEW

**Comment by boneskull** [comment]
Yeah, I don't know how to test this.  Maybe we just merge it and see if it does anything.

**Comment by boneskull** [comment]
The reason is because we (I?) tend to get a fair amount of email from people wondering why their logo isn't on the site.  Since we're only fetching the logos and links at build time now, we need a nightly job to keep it up-to-date.

**Comment by nicojs** [comment]
> Yeah, I don't know how to test this. Maybe we just merge it and see if it does anything.

Why not configure it to run on a `push` action once. When you see it works, you can remove the push action.

**Comment by boneskull** [comment]
I want to merge this, but given that all deploys seem to be failing atm, that needs fixing first

**Comment by boneskull** [comment]
hmm, maybe it's fixed now.

**Comment by boneskull** [comment]
I think `mochajs.org` needs fast-forwarding.

**Comment by boneskull** [comment]
OK, I see why it's breaking.  See https://github.com/mochajs/mocha/pull/4339

The svg's on OC's side are broken

**Pull request merged**
