### PR TITLE
fixed redundant images folders

### PR DESCRIPTION
**Pull request by DavNej**
This is my first contribution and here is what I did.

- Looked everywhere in the code to see where each image was used.
- Changed paths, organised the "mocha/images" folder with a subfolder "growl"
- Removed unused images and folders.

WARN: I can't figure out how to run a test to ensure that what I did was correct. Please review and tell me if I forgot something or if I should proceed otherwise.

Thanks :)

### CODE REVIEW

**Comment by Nokel81** [comment]
Two things, the first is why did you move them into a sub folder and the second. Are all those files really not needed? Some of the files may not be referenced explicitly but implicitly because they are hosted somewhere else. For instance the logo is used in the readme but has a version in the repo so that (I assume) it can be updated later if wanted

**Comment by outsideris** [comment]
I think we should keep the images. It is assets which don't mean only to use it in code.

**Comment by boneskull** [comment]
I feel like the original issue should have been more specific.

**Comment by DavNej** [comment]
Hi @boneskull 

I replaced all deleted images and placed them in the assets folder. I placed in it `media/logo.svg` and `growl/`. I also changed the paths in `bin/_mocha` and in `lib/mocha.js` so we still have only one media folder.

Furthermore, I already signed the CLA and when I revisit the page to sign, they tell me I already did.

**Comment by outsideris** [comment]
@DavNej Thank you for your contribution.
We will update `contributors` in `package.json` with automatic script, see https://github.com/mochajs/mocha/pull/3290.
Please remove your name in `package.json`. Don't worry. We will update your name in our `package.json`.

I'm not sure why `license/cla` said that you are not signed yet.

**Comment by boneskull** [comment]
> We will update contributors in package.json with automatic script, see #3290.

IMO it's not necessary for anyone to remove themselves from the `package.json`.  The script will overwrite it anyway.

**Comment by boneskull** [comment]
@kborchers can you please check on the CLA status for this?

**Comment by boneskull** [comment]
@davNej I wonder if you could amend your commit then force push?  That might "jiggle the handle" on the CLA system, as it were.

```bash
$ git commit --amend --reuse-message=HEAD
$ git push -f
```

**Comment by kborchers** [comment]
The issue with the CLA signature is likely that the user in the commit doesn't match the user that signed. If you look at the commit, the user is not recognized by GitHub and doesn't match the user that opened the PR and likely signed the CLA. The commit will need to be updated with the correct user and email or the CLA needs to be signed with the user on the commit.

**Comment by DavNej** [comment]
Hi, I had some login issues I fixed. In order to have some change to commit I removed my name from the `contributors` in `package.json`, merged, and then push (with 3 commits. Sorry). Now the signature of the CLA should be ok.
I learnt stuff :)

**Comment by outsideris** [comment]
DavNej signed CLA, but David Nejar doesn't. I think you should update author for all commits.

**Comment by DavNej** [comment]
Hi,
I tried the following commands in order to change the author for the first four commits but it doesnt seems to work.
I ran:
`git rebase -i HEAD~6`
then inserted
`exec git commit --amend --author="DavNej <davnej.dev@gmail.com>" -C HEAD` after each commit I wanted to change in the temporary file I was prompted. I saved and closed, then ran
`git rebase --continue`
Have I done something wrong?

**Comment by boneskull** [comment]
@DavNej I'm not sure.  Just rebase interactively and squash all commits with the new author.  I'd recommend doing this in your Mocha working copy: 

```bash
$ git config user.name 'DavNej'
$ git config user.email 'davnej.dev@gmail.com'
```

...then squashing.

**Comment by DavNej** [comment]
@boneskull 
Yes I realised that was the problem of the first commits and I took care of that. now I would want to squah all the previous commits into one identified by DavNej (who signed the CLA).
is there a proper way to squash them all?

**Comment by outsideris** [comment]
You can squash them all with `git rebase`.
And you can author for the commit like:

```
$  git commit --amend --author="DavNej <davnej.dev@gmail.com>"
```

**Comment by boneskull** [comment]
@DavNej Here's a [decent tutorial](https://davidwalsh.name/squash-commits-git) on squashing.

**Comment by boneskull** [comment]
This will be ready to merge once we sort out the squash & CLA business.

**Comment by DavNej** [comment]
After some struggle and some useful learning, I squashed the commits leaving only the 2 main commits. Thank you very much for your patience. Peace :)

**Comment by outsideris** [comment]
I'm not sure when I can merge PR yet. So, I leave this because this is ready to merge. @boneskull

**Comment by boneskull** [comment]
I'll need to manually merge this anyway.

**Comment by boneskull** [comment]
landed in ad54763

**Comment by boneskull** [comment]
@DavNej Thanks!

**Comment by plroebuck** [comment]
See ad54763 inline notes for bug introduced with this merge.

**Pull request closed without merging**
