### PR TITLE
Allow prepending hooks beforeAll/afterAll/beforeEach/afterEach

### PR DESCRIPTION
**Pull request by carsonreinke**
A `prepend` argument allows for a hook to placed in front of the list.

Thoughts?  Let me know.

### CODE REVIEW

**Comment by Munter** [comment]
Since you've obviously gone through a lot of trouble to implement this, maybe you could also spend a bit of time trying to clarify the use case that fuels the need for this change? I'm having a hard time understanding what this is about

**Comment by carsonreinke** [comment]
@Munter this is in case you need to push a hook on to beginning of the list.  Came across this issue using a set of shared tests, but a particular test case required a `beforeEach` hook ahead of the shared hooks.

Maybe it is better to just allow access the array of hooks instead.

**Comment by boneskull** [comment]
> @Munter this is in case you need to push a hook on to beginning of the list

Why would this be necessary?

**Comment by boneskull** [comment]
inactive

**Pull request closed without merging**
