### PR TITLE
Add support for node v8 option 'prof' parameter (#4433)

### PR DESCRIPTION
**Pull request by Donghoon759**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

I modified `--prof` to be considered as a 'Node' flag so that Node can handle it.

### Alternate Designs

N/A

### Why should this be in core?

#4433 

### Benefits

Users can pass `--prof` argument to mocha and Node can handle it by profiling.

### Possible Drawbacks

N/A

### Applicable issues

#4433

### CODE REVIEW

**Comment by boneskull** [comment]
Ahh, yes, the v8 options... they refuse to expose them in any sort of public API.

**Review by boneskull — COMMENTED** [review]
Thanks!

So, I don't think this is an actual _bug_.  It is not a `node` option, e.g., is not exposed in `process.allowedNodeEnvironmentFlags`.  The ones whitelisted here are _historical_ and remain for backwards compatibility only--they are V8 flags which Mocha previously hard-coded (before `process.allowedNodeEnvrionmentFlags` landed).  All V8 options should be accessible via `--v8-<option-name>`, e.g., `--v8-prof`.

I'm inclined to _not_ accept this PR, because it's really a slippery slope--taken to its logical conclusion, we end up hard-coding the entire list of V8 options.

Thoughts?  @mochajs/core @outsideris

**Comment by juergba** [comment]
We shouldn't add this option to our special CLI supported list. regex expressions like this one are a nightmare to maintain anyway.
I don't know why in Node's docs `--prof` is listed as option, but isn't exposed in `process.allowedNodeEnvironmentFlags`. There must be a reason which I don't understand.

We should deprecate the complete list of historically supported options and instruct users to use `NODE_OPTIONS` instead. I haven't checked our historically supported list, but even some V8 options could be passed to Node that way. `--perf-prof`yes, but `--prof` no.

**Comment by boneskull** [comment]
@juergba it's because `--prof` is not a Node option _per se_--it's a V8 option.  Node supports a subset of these "natively", and a subset of those in `NODE_OPTIONS`.

Further, `NODE_OPTIONS` and the allowed command-line flags are not 1:1.  For example, `--preserve-symlinks` is a command-line option for node, but it is _not_ allowed in `NODE_OPTIONS`.

For this reason, I don't think we can just do away with it entirely and demand users use `NODE_OPTIONS`.

**Comment by boneskull** [comment]
Either way, sounds like we have some agreement that we don't want to merge this.  

The reasoning is:

1. There are multiple workarounds; `--v8-prof` and `NODE_OPTIONS=--prof`
1. The regex is "historical" and should not be updated (I didn't check to see if this is actually in the code comments there, but it should be).

Thank you!

**Pull request closed without merging**
