### PR TITLE
add OpenJS Foundation logo to website

### PR DESCRIPTION
**Pull request by boneskull**
As per mochajs/admin#7, we need to add the logo to our site.

I've received the SVG from the foundation, so here it is.

Screenshot:

image

### CODE REVIEW

**Comment by boneskull** [comment]
There were some errant tabs that got converted to spaces as well.

**Comment by juergba** [comment]
The deploy preview doesn't show any OpenJS Foundation logo, only Matomo is visible.

**Comment by boneskull** [comment]
weird. will look into it

**Comment by boneskull** [comment]
I don't even see the file listed in the netlify deploy log... hm.

**Comment by outsideris** [comment]
Me neither. It seems netlify doesn't build on this PR. I can't find a button to rebuild a preview without cache.

**Comment by boneskull** [comment]
OK, you can see it in the preview now, for whatever reason.

**Comment by boneskull** [comment]
WFM.  coveralls is hinky, but whatever.

**Pull request merged**
