### PR TITLE
update copyright & trademark notices per OJSF; closes #4145

### LINKED ISSUE #4145: update copyright text for OpenJS Foundation & website footer
as part of our onboarding process, the last thing we need to do is update our copyrights.  The Foundation has given its projects the guidance we need to do this; see https://github.com/openjs-foundation/cross-project-council/pull/414.

> Note: As of this writing, the above PR has not yet been merged, but there's unlikely to be any material changes to what the copyright notices should look like, as they have been approved by the board (and the board is unlikely to revisit based on the feedback in the PR).

I'll send a PR to get this updated.

### PR DESCRIPTION
**Pull request by boneskull**
- made footer responsive
- made matomo & openjsf logos responsive
- remove `target="_blank"` since people can decide if they want to open a tab

Ref: #4145

### CODE REVIEW

**Comment by boneskull** [comment]
look at me, mr fancy pants

see the responsiveness!!!

**Comment by boneskull** [comment]
@mochajs/core will merge this in the next day or two unless someone cares to review

**Comment by craigtaub** [comment]
> Remove target="_blank" since people can decide if they want to open a tab

I'd prefer for them to new tab. Speaking from experience, I occasionally get annoyed when they don't.

**Comment by boneskull** [comment]
> I'd prefer for them to new tab. Speaking from experience, I occasionally get annoyed when they don't.

my rationale is that it's pretty trivial to open stuff in a new tab if you want to, nowadays.  think about it like this: how do you open a link _in the same tab_ if that link has `target="_blank"`?  :smile:

**Pull request merged**
