### PR TITLE
Update js-yaml from 3.13.0 to 3.13.1

### LINKED ISSUE #3876: js-yaml needs to be updated (and should have a range version)
### Description
js-yaml has a new security vulnerability: https://www.npmjs.com/advisories/813

For some reason, a specific version (3.13.0) is being specified in package.json. Why isn't this a range?

### Steps to Reproduce
Install the latest version of mocha, then run `yarn audit`.

**Expected behavior:**
No vulnerabilities found.

**Actual behavior:**
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mocha                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ mocha > js-yaml                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/813                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### Versions
mocha 6.1.3

### PR DESCRIPTION
**Pull request by bjornstar**
### Description of the Change

Update the dependency, `js-yaml` from v3.13.0 to v3.13.1 to address a security advisory: https://npmjs.com/advisories/813

### Alternate Designs

N/A

### Why should this be in core?

N/A

### Benefits

Improved security

### Possible Drawbacks

None

### Applicable issues

Fixes #3876

### CODE REVIEW

**Comment by GoodVincentTu** [comment]
Just saw the code injection alert today, it's glad to see the issue has been resolved. @Munter I was wondering when will the next version be released? Much appreciated.

**Comment by markowsiak** [comment]
@Munter https://github.com/mochajs/mocha/pull/3878 also covers this change

**Comment by shawnpetros** [comment]
So, is there a new version of mocha getting released soon?

**Comment by boneskull** [comment]
@juergba @craigtaub feel free to cut a patch release for this; don't need to wait on the other stuff in the milestone (we can just leave the milestone as-is)

May get a chance to do it tomorrow or Friday otherwise.

**Comment by boneskull** [comment]
also @plroebuck and @munter if you have any interest in cutting releases, please let me know.

**Pull request merged**
