### PR TITLE
build mochajs.org with Jekyll; closes #1640

### LINKED ISSUE #1640: jekyll gh-pages
This is in progress.  If anyone knows how I can use syntax highlighting *and* valid GFM markdown in Jekyll, please let me know.

### PR DESCRIPTION
**Pull request by boneskull**
[Demo](http://boneskull.com/mocha)

Lots of stuff here, but the main things:

- use Jekyll
- convert `index.md` to *actual GFM Markdown*
- a lot of edits of the documentation, including, but not limited to:
  - reorganization
  - grammar fixes
  - code style fixes
  - rewording confusing sentences
  - add a couple more examples
  - dynamically generate TOC
  - use CDNs for JS, though there's basically none

I've taken every effort to make the site look as close to the current version as it does now, and keep it compatible with old browsers.  However, I was not able to reuse the syntax highlighting scheme, as highlighting is now done by Pygments.

screenshot 1

screenshot 2

### CODE REVIEW

**Comment by boneskull** [comment]
I'm not sure why it doesn't want to merge automatically.  This is rebased on top of 5e1fabd

**Comment by boneskull** [comment]
somebody (not me) needs to look thru [the demo site](http://boneskull.com/mocha) for problems.

**Comment by boneskull** [comment]
ping @jbnicolai

**Comment by jbnicolai** [comment]
I'll have a go ;)

**Comment by rstacruz** [comment]
ping! any updates here? :)

**Comment by boneskull** [comment]
I've updated this PR:

1.  Changed module which generates ToC to [something I maintain](https://www.npmjs.com/package/markdown-toc-index), in case it needs fixing.
2.  Create heading `id`'s via `redcarpet` instead of JS
3.  Fix `Gemfile` issue
4.  Reduce depth of ToC, so it should match more closely with the original

The only stylistic difference that I can see is that the syntax highlighting isn't the same (imo, it's better).

Of course, there's all the changes to the actual documentation and code examples itself, too.

@rstacruz Sorry about this; one of us is going to have to throw out work.

**Comment by boneskull** [comment]
cc @jbni

**Comment by jbnicolai** [comment]
http://boneskull.com/mocha/#-w-watch seems broken in the TOC (should have two dashes between 'w' and 'watch)

**Comment by jbnicolai** [comment]
To be honest, I'm not a big fan of the 2 level of nesting layout in the TOC. Especially on a smaller width is looks very confusing, eg:

screen shot 2015-07-05 at 12 30 52

How about we limit it to only show top-level entries?

**Comment by jbnicolai** [comment]
The Gitter image now takes up more space, I think I prefer the old style.

New: 
screen shot 2015-07-05 at 12 32 57


Old:
screen shot 2015-07-05 at 12 32 57

**Comment by boneskull** [comment]
@jbnicolai that's odd... why would you see two levels of nesting?

**Comment by boneskull** [comment]
@jbnicolai I know why.  because I didn't rebase into my gh-pages branch.

**Comment by boneskull** [comment]
@jbnicolai you may wish to try to build the site yourself as well.  but anyway, I updated [boneskull.com/mocha](http://boneskull.com/mocha) with the new code.

**Comment by jbnicolai** [comment]
@boneskull I have, see http://blog.jbnicolai.com/mocha/

I suggest we go with #1777 though, as it includes both your branch, the competing branch and some additional changes :)

**Comment by boneskull** [comment]
@jbnicolai Yes, let's go with your code anyway.

**Pull request closed without merging**
