### PR TITLE
upgrade assetgraph-builder with fixes

### PR DESCRIPTION
**Pull request by boneskull**
from @papandreou

### CODE REVIEW

**Comment by papandreou** [comment]
@boneskull, I tried to update the lockfile, but it produces a huge number of changes: https://github.com/papandreou/mocha/commit/17ebed15394b5fc9e6e7445876d0de4770fde5a4

I used `npm@5.6.0` to update it -- do you remember which version the lockfile was generated with? Maybe it'll help if I use that.

**Comment by outsideris** [comment]
Additioanally, `buildProduction` took much longer than before this PR in my local.

before:
```
 ✔ 0.006 secs: reviewSubResourceIntegrity
 ✔ 47.618 secs: buildProduction
 ✔ 1.595 secs: writeAssetsToDisc
```

after:
```
 ✔ 2.965 secs: reviewSubResourceIntegrity
 ✔ 307.252 secs: buildProduction
 ✔ 2.071 secs: writeAssetsToDisc
```

**Comment by outsideris** [comment]
I didn't test it with @papandreou 's commit.

**Comment by papandreou** [comment]
@outsideris, thanks, will look into the `undefined` thing.

I'm aware that it's still slower than ag-b 5. I will get around to trace down the remaining performance regressions.

**Comment by outsideris** [comment]
I confirmed `undefined-1.d41d8cd98f` is fixed.

However, it doesn't make `static` directory at all. So, every references under `static/` are broken.

**Comment by papandreou** [comment]
@outsideris, you're right, I can reproduce that. It's a problem with the `--canonicalroot` switch. Looking into it.

**Comment by papandreou** [comment]
@outsideris, fixed now. Thanks for letting me know.

**Comment by outsideris** [comment]
CI is failed. 

```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's assetgraph-builder@5.9.1 does not satisfy assetgraph-builder@^6.3.4
npm ERR! Invalid: lock file's svgo@0.7.2 does not satisfy svgo@^1.0.5
```

**Comment by papandreou** [comment]
@outsideris, I also ran into that and commented: https://github.com/mochajs/mocha/pull/3412#issuecomment-395909020

**Comment by outsideris** [comment]
@papandreou I missed that comment.
The precache job ran under node v10, so npm version is 6.1.0.

You can see it in [the job logs](https://travis-ci.org/mochajs/mocha/jobs/390507544).

```
$ npm --version
6.1.0
```

In my local, `npm ci --ignore-scripts` is works with npm@6.1.0.

**Comment by papandreou** [comment]
@outsideris, ah, thanks. I've updated `package-lock.json` now by running a fresh `npm install` with npm 6.1.0.

Still seems like an awful lot of changes, though.

**Comment by papandreou** [comment]
Improved the performance further in assetgraph-builder, here's the current build time on my laptop:

```
 ✔ 117.447 secs: buildProduction
```

**Comment by papandreou** [comment]
@outsideris, weird that it didn't improve more on your machine. I can't explain that.

**Comment by papandreou** [comment]
@outsideris, thanks for trying. I guess that just means I'm not done yet ;)

**Comment by plroebuck** [comment]
@Munter, self-assign this one.

**Comment by plroebuck** [comment]
@papandreou, any status update on where this stands?

**Comment by plroebuck** [comment]
Assuming actual time is closer to what you see (than Outsider), my question was to see if there were any other related bugs to shake out?

**Comment by papandreou** [comment]
I'm not aware of any other issues, no.

**Comment by boneskull** [comment]
I'm going to close this and retry with the latest version.

**Pull request closed without merging**
