### PR TITLE
[Do not merge] Adds initial draft for the release notes.

### PR DESCRIPTION
**Pull request by jbnicolai**
I think it's about time to make a new minor release of mocha.

@mochajs/mocha anything we should wait for to still make it into the release? Anything we still need to test more thoroughly? Did I forget something in the changelog?

### CODE REVIEW

**Comment by sunesimonsen** [comment]
Hi @jbnicolai,

A new release sounds great, but I think this issue has to be fixed before the release: #1789

**Comment by jbnicolai** [comment]
@sunesimonsen absolutely, thanks for both testing the bleeding edge, finding and fixing the issue :)

**Comment by jbnicolai** [comment]
Suggestion: rather than create a minor release, bump it to 3.0.0 and include #1632 and #1481. The other milestone V3.0.0 could be postponed to the next major release.

**Comment by sunesimonsen** [comment]
@jbnicolai happy I could help. I agree that the html-reporter needs some kind of test suite, it is just too easy to overlook (#1732).

**Comment by boneskull** [comment]
:+1:

**Comment by danielstjules** [comment]
Closing as the release notes were updated in https://github.com/mochajs/mocha/commit/ee0a55b572d7da7dd8b7abc418d594602692bbed :)

**Pull request closed without merging**
