### PR TITLE
#1417 - displaying actual error instead of incorrect done() called mu…

### PR DESCRIPTION
**Pull request by davija**
Patch for issue 1417 - Error in "done() called multiple times" assumptions.

The error was hidden by not passing in the exiting error from the context which led to an incorrect error stating done() has been called multiple times.

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR! Could you write a regression test that would fail prior to this PR? E.g. in https://github.com/mochajs/mocha/blob/master/test/integration/regression.js

**Comment by davija** [comment]
regression test has been added

**Comment by hollomancer** [comment]
@davija - Please rebase, and we'll look at it again.

**Comment by boneskull** [comment]
Closing as old, thanks though!

**Pull request closed without merging**
