### PR TITLE
Display stack for uncaught errors in the browser

### LINKED ISSUE #5106: 🐛 Bug: Browser doesn't include call stack for global uncaught errors
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [X] I want to provide a PR to resolve this

### Expected

When an uncaught error occurs during a test in browsers, you'd expect to see the call stack. That's useful.

```plaintext
Error: Oh no!
    at inner (test.example.js:8:15)
```

### Actual

Mocha's browser error handling code was written before browsers gave nice stacks (https://github.com/mochajs/mocha/commit/eb58761bb3346d2597e8365e60273417127b72c4).

```plaintext
Error: Error: Oh no! (http://127.0.0.1:8081/test.example.js:8)
```

### Minimal, Reproducible Example

Using a minimal browser setup such as in https://github.com/mochajs/mocha-examples/pull/72:

```js
it("example", (done) => {
    function inner() {
        throw new Error("Oh no!");
    }

    setTimeout(inner);
});
```

### Versions

Mocha: 10.3.0

### Additional Info

This was filed long ago in #2167, then a fix proposed in #3952. Since #2167 is quite old, re-filing to be more current.

### PR DESCRIPTION
**Pull request by prust**
### Description of the Change

This change captures the stack of uncaught exceptions in the browser, so it will be displayed in Mocha. Before this change, uncaught exceptions in the browser are displayed with a URL and line number, but without a stack:

no-stack

This pull request updates the global error handler for the browser so that the stack is captured:

with-stack

The issue was that the browser-specific hook for uncaughtExceptions in `browser-entry.js` was using the pre-2014 three-parameter `window.onerror`, which only provides the error message, the URL and the line number. [In 2014](https://danlimerick.wordpress.com/2014/01/18/how-to-catch-javascript-errors-with-window-onerror-even-on-chrome-and-firefox/), two more parameters were added in both [the spec](http://www.whatwg.org/specs/web-apps/current-work/multipage/webappapis.html#errorevent) and Chrome, with other browsers following shortly thereafter (including IE11) -- the last of these parameters is the Error object itself, which has a populated stack.

### Alternate Designs

The design could be simplified by only supporting the five-parameter `onerror()`, but since mocha is used in all sorts of environments, I figured it was safest to use the `err` parameter if it exists and to fall back to the previous functionality if it doesn't.

The design could be a little more complex if it is important to preserve the message provided to the `onerror` handler, which -- in Chrome, at least -- has an extra "Uncaught Error: " prefix. This would add a couple more lines to the top of `onerror` in `browser-entry.js`:

```javascript
if (err)
  err.message = msg;
```

### Why should this be in core?

This would bring consistency to the quality of error reporting in mocha's core (uncaught exceptions in Node and caught exceptions in Node and the Browser all include stacks).

### Benefits

The inclusion of the stack will make it easier for developers to determine the cause of the error.

### Possible Drawbacks

With this particular design choice, if a mocha user was grepping or testing for the browser-supplied "Uncaught Error:" prefix in a browser test, this change would cause it to not be found. If this is important, the two lines mentioned above in "Alternate Designs" could be added.

### Applicable issues

* I think #2167 may be fixed by this pull request (but I'm not familiar with AMD/RequireJS, so I'm not in a good position to test it)

Regarding semver, I think I would call this an enhancement (providing stack traces for uncaught exceptions). I suppose it could be considered a breaking change, since it is hypothetically possible that someone is relying on the browser-supplied "Uncaught Error:" prefix somehow, but this is highly unlikely. If it's a concern, it could be address by the 2-line fix above.

### Tests

I did write a browser-specific test for this (which was orders of magnitude harder than fixing the issue itself), but the uncaught exception is causing the test to fail. I tried passing `--allow-uncaught true/false` in the relevant `mocha.opts`, as well as `mocha.allowUncaught()`, but neither made a difference.

Perhaps I should try putting the test with the `allowUncaught` or `uncaught()` tests in `runner.spec.js`, but it looks like the `allowUncaught` tests always throw an error somewhere that it will be caught, and the `uncaught()` tests don't actually throw errors (they just pass an error object directly to `uncaught()`), the former would probably run into the same issue I'm currently running into and the latter wouldn't exercise the code in question.

If someone with familiarity with the mocha's exception-testing tests could lend a hand or direct me in a direction that is likely to work, I would appreciate it.

Fixes #5106.

### CODE REVIEW

**Comment by prust** [comment]
Update: @boneskull outlines the issue & how to fix it beautifully in https://github.com/mochajs/mocha/pull/2983#issuecomment-350428522 and this is already being done in `throw.spec.js`. I'm going to follow suit here (and/or move this test into `throw.spec.js`)

**Comment by Lindsay-Needs-Sleep** [comment]
@juergba 
Can you review this issue?

I have been using this improvement.  It is very useful.  I would like to see it in the next release.

I have also run ‘npm run test’ on this branch, everything passes.

**Comment by juergba** [comment]
@Lindsay-Needs-Sleep I don't have the browser knowledge to review this PR.
Mocha is still supporting IE11, [this: Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) doesn't help neither.

**Comment by Lindsay-Needs-Sleep** [comment]
@juergba Do you know who might have the knowledge (and power to review this?)

Due to the way javascript works, if a browser does not support the 4th and 5th arguments of `onerror` they will just have a value of `undefined` when `onerror` is triggered.  This is fine because in that situation, this line:
```
fn(err || new Error(msg + ' (' + url + ':' + line + ')'));
```
will evaluate to this:
```
fn(new Error(msg + ' (' + url + ':' + line + ')'));
```
Which is exactly what happened before this change.

Basically, this change just results in an improved error object for browsers that do support the 4th and 5th args.  Browsers that don't, will be unaffected.

(Also, I did try out IE11.  It does support the 4th and 5th args! Yay!)

**Comment by juergba** [comment]
@prust Are you still interested in this PR?
I'm trying to understand and finally get it merged.

If yes, could you please rebase? I would like to push your branch to our repo, to make sure all tests do pass correctly. There are additional tests running (eg IE11).

Does this PR solve #1979 ?

**Comment by juergba** [comment]
I did some testing in Chrome with `fullTrace: true` and `reporter: 'spec'`:
```js
describe('uncaught', function() {
  it('throw delayed error', (done) => {
    setTimeout(() => {
      throw new Error('Whoops!');
    }, 10)
    setTimeout(done, 10);
  });
```
Now there is even less stack information printed than before. I guess skipping the `msg` is not a good idea. An `uncaughtException` does not always mean that the runner throws and aborts. In above example the handler recovers from the error (fails the still open test) and then keeps going. In this case we loose stack information now.
I will do more testing tomorrow.

**Comment by JoshuaKGoldberg** [comment]
Moving over to #5107 with a co-authored-by attribution. Cheers! 🤎

**Comment by JoshuaKGoldberg** [comment]
Ah @prust hello! I'd just made a new PR because I didn't have permissions to push to [`CSNW:master`](https://github.com/CSNW/mocha/tree/master). If you want to make a new PR from another branch I'm happy to switch to that one, to preserve attribution for you as the author. No worries if you don't have the time though. 🙂

**Comment by JoshuaKGoldberg** [comment]
#5107 is merged; we'll release a new version with the fix soon. 🚀

**Comment by prust** [comment]
Thanks @JoshuaKGoldberg!

**Pull request closed without merging**
