### PR TITLE
Added option to allow unhandled exceptions to propagate in the browser

### PR DESCRIPTION
**Pull request by amsul**
Related to #553

This adds the `mocha.allowUncaught` method.

When the method **isn’t** invoked, the console is empty:

When the method **is** invoked, the console shows the unhandled exception:

### CODE REVIEW

**Comment by garrett-gottlieb** [comment]
+1

**Comment by boneskull** [comment]
I don't get it.  Why don't we just do both?

**Comment by amsul** [comment]
@boneskull now it does :+1:

**Comment by boneskull** [comment]
@mochajs/mocha seems like a good idea to me for minor release.  if there is no disagreement I will merge this

**Comment by boneskull** [comment]
@amsul can you rebase on top of branch `v2.3.0`?

**Comment by amsul** [comment]
@boneskull done

**Comment by a8m** [comment]
lgtm.
Can you please squash your commits @amsul ?

**Comment by boneskull** [comment]
@amsul I don't think you can actually change which branch you're making a PR against, so you may want to actually open a new one.  I'm going to close this to make sure it doesn't get accidentally merged.

1.  Checkout the `v2.3.0` branch
2.  Probably just cherry-pick changeset 10dcd85 on top of it
3.  Create new PR against `v2.3.0` branch

Thanks!

**Pull request closed without merging**
