### PR TITLE
lazy/nolazy v8 switch

### PR DESCRIPTION
**Pull request by moander**

### CODE REVIEW

**Comment by danielstjules** [comment]
I'd like to avoid adding options like this. Otherwise we risk the same problem we were having with the harmony flags. With node v4, I see over 300 v8 options. Related: https://github.com/mochajs/mocha/issues/1846  (though it only mentioned harmony flags)

**Comment by moander** [comment]
It's related to the exposed debug-brk / profiler flags, so I think nolazy should be exposed as well.

**Comment by danielstjules** [comment]
I agree, would just prefer a solution that accommodates all v8 options rather than slowly building up to a 300+ line long switch.

**Comment by moander** [comment]
Would it be an acceptable solution to pass all unknown options down to node?

**Comment by danielstjules** [comment]
https://github.com/mochajs/mocha/issues/1846#issuecomment-139113704 I think that'd work as a temporary solution :)

**Pull request closed without merging**
