### PR TITLE
Description meta tag

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Provide a description for search engines, they tend to like it.

### CODE REVIEW

**Comment by MartijnCuppens** [comment]
No problem, thanks for the tip!

**Comment by boneskull** [comment]
Thanks!

**Comment by KAndersonUS** [comment]
Possibly related to this PR, the description on Google right now is raw HTML:

image

I will open a new proper issue if I can reproduce over the weekend, but I wanted to quickly document the issue somewhere.

**Comment by MartijnCuppens** [comment]
@KAndersonUS, I think this change is not released yet.

**Pull request merged**
