### PR TITLE
chore(deps/security): upgrade to latest stable

### LINKED ISSUE #4410: Flat 4.1.0 is deprecated causing an npm warn
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

when installing mocha 8.1.1, npm warns that flat 4.1.0 is deprecated.

### Steps to Reproduce

run `npm i -g  mocha`

**Expected behavior:** [What you expect to happen]

No warns

**Actual behavior:** [What actually happens]

npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.

**Reproduces how often:** [What percentage of the time does it reproduce?]

all the time

### Versions

mocha 8.1.1
node 12
ubuntu bionic

### PR DESCRIPTION
**Pull request by AviVahl**
### Description of the Change

- Upgrade dependencies to latest stable versions.
- Replace `rollup-plugin-node-builtins` with  `rollup-plugin-node-polyfills`, as former causes audit failures and latter seems just a bit* more maintained.

### Alternate Designs

Consider using `dependabot` or `renovate` to automatically open PRs for updates.

### Why should this be in core?

To resolve consumer deprecation messages when installing mocha:
`warning mocha > yargs-unparser > flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.`

To reduce the number of repo audit failures from:
`found 51 vulnerabilities (5 low, 2 moderate, 44 high) in 2841 scanned packages`
to:
`found 3 low severity vulnerabilities in 2629 scanned packages`

### Benefits

Better deduping for the other packages.

### Possible Drawbacks

None that I'm aware.

### Applicable issues

closes #4410

### CODE REVIEW

**Comment by AviVahl** [comment]
Not sure about the `netlify/mocha/deploy-preview` check. Tells me:
> Page not found. You might not have permissions to see this page.

**Review by outsideris — APPROVED** [review]
> Not sure about the netlify/mocha/deploy-preview check. Tells me:

Netlify failed caused by an opencollective issue.

**Comment by outsideris** [comment]
OpenCollective had internal server errors for some avatar images. It seems OC fixed the issue.
So, I re-ran netlify build.

**Comment by martinoppitz** [comment]
Thanks for this fast PR!!!

Note: There is a breaking change inside! https://github.com/yargs/yargs-unparser/releases/tag/v2.0.0

We need the mocha fix for our https://www.npmjs.com/package/@leanup/cli#dependencies.

**Comment by AviVahl** [comment]
It's not breaking, as mocha already dropped these node versions.

**Comment by boneskull** [comment]
need to run this against all browsers...sigh.

**Comment by boneskull** [comment]
[build here](https://travis-ci.org/github/mochajs/mocha/builds/733434524)

**Comment by AviVahl** [comment]
@boneskull correct me if I'm wrong, but the failures I'm seeing don't seem to relate to the upgrades. does `master` pass?

**Comment by AviVahl** [comment]
rebased to current `master`. squashed into a single commit. regenerated lock file. (lock file diff has a nice de-duping effect)

**Comment by AviVahl** [comment]
`npm audit` on `master`:
`found 51 vulnerabilities (5 low, 2 moderate, 44 high) in 2841 scanned packages`

`npm audit` on this PR:
`found 6 vulnerabilities (3 low, 2 moderate, 1 high) in 2669 scanned packages`

**Comment by AviVahl** [comment]
Pushed another commit which reduces the audit failures to:
`found 3 low severity vulnerabilities in 2629 scanned packages`

**Comment by AviVahl** [comment]
this does not include `worker-pool@6.0.2`, as https://github.com/mochajs/mocha/pull/4465 handles that.

**Comment by boneskull** [comment]
this now has conflicts

**Comment by boneskull** [comment]
I think you just need to rebase to get the workerpool update

**Comment by AviVahl** [comment]
will rebase

**Comment by AviVahl** [comment]
@boneskull any idea if the flakiness related to the workerpool/parallel test changes?

**Comment by boneskull** [comment]
yeah failure is related to that, but unsure what's wrong. haven't had it fail before! could be something in the lockfile or the github actions cache... or just windows flake or windows flake on a specific node version (again, which hasn't surfaced). 

we need to be certain the failure is unrelated though. I can't view the diff of the lockfile on my phone, maybe you can diff the workerpool subtree with what's in `master` and assert it's identical. if so, then it's likely unrelated to the changes here

**Comment by boneskull** [comment]
subtree meaning in the lockfile not on disk

**Comment by AviVahl** [comment]
I checked the lockfile. both `master` and the branch have the same version of workerpool (6.0.2). nothing special there.

**Comment by AviVahl** [comment]
rebased to `master` again, to see if failure is consistent.

**Comment by AviVahl** [comment]
Failure did not occur post rebase.

**Comment by boneskull** [comment]
I _hope_ this is not the start of consistent flake.  anyway, ty

**Pull request merged**
