### PR TITLE
Allow skip from test context for #332

### PR DESCRIPTION
**Pull request by cmbuckley**
Opening a PR to get some feedback for this implementation.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Needs rebasing again. I will merge if you rebase. Sorry for the hassle.

**Comment by cmbuckley** [comment]
Rebased again, no issues or conflicts :smile:

**Comment by dasilvacontin** [comment]
Thanks!

**Comment by artkoshelev** [comment]
any chances to see new version with this feature included soon?

**Comment by maggiesavovska** [comment]
I can't get this to work with webdriver.io (see below example). Also, was this really merged? This feature doesn't seem to be present in the current version of mocha?? 

`it('should be skipped async', function(done){
var self = this;
	setTimeout(function(){
		self.skip(); //works -- test prints as pending in terminal
	},1000);

	driver.waitForExist('body').then(function(){
		console.log(self); //correct
		self.skip.bind(self)(); //doesn't work -- test prints as error in terminal
	});
})`

**Comment by cmbuckley** [comment]
This was merged in 6402fff so is present in 2.2.0+. Any more information on the error? May be worth filing a separate issue.

**Comment by dasilvacontin** [comment]
@maggiesavovska what's the error? Is the test timing out, or is it something else?

**Comment by dasilvacontin** [comment]
I just experienced this:

async.js
```js
it('should be skipped async', function (done) {
  const self = this
  setTimeout(function () {
    self.skip()
  }, 1000)
})
```

```bash
$ mocha test/async.js


  1) should be skipped async

  0 passing (1s)
  1 failing

  1)  should be skipped async:
     Error: the object {
  "message": [undefined]
  "uncaught": true
} was thrown, throw an Error :)
```

**Comment by maggiesavovska** [comment]
@dasilvacontin + @cmbuckley: Please forget what I said about webdriver.io. I think it's a general issue. I get the same as @dasilvacontin (uncaught error with undefined message). I actually was only able to get this to work at all by modifying the current version of mocha so I'm guessing this feature is somehow broken due to recent changes (regardless of whether its used with webdriver.io promise or not).

**Comment by maggiesavovska** [comment]
Hi, sorry to be a bug, but were you able to confirm that this feature isn't currently working? I really need this for the project I'm working on now. Thanks!

**Comment by boneskull** [comment]
Well, I can confirm @dasilvacontin 's code is throwing that error

**Comment by boneskull** [comment]
*Is* this a regression?  Did we ever have this support for async tests?

**Pull request merged**
