### PR TITLE
Remove unnecessary conditional

### PR DESCRIPTION
**Pull request by jakecraige**
This conditional was no longer needed

Based on this comment https://github.com/mochajs/mocha/pull/1537/files#r24287807

### CODE REVIEW

**Comment by a8m** [comment]
@jakecraige IMO the more sense way is to `git reset HEAD~2` 2 commit before 1197fa7cb050b7d67468ae612a14f9c0d553db34

**Comment by jakecraige** [comment]
@a8m I feel weird about rewriting history, but if that's what y'all want to do, no worries. I just did it. I guess you'll have to manually merge and force push since it causes conflicts

**Comment by boneskull** [comment]
No, rewriting history is probably not a good idea against `master`

**Comment by danielstjules** [comment]
Closing as this was resolve in https://github.com/mochajs/mocha/commit/558191d964e860eaddd6432e8fe5a86bad7781be#diff-b3b53682a18f203ac8d29b0e277cad26R205 Thanks! :)

**Pull request closed without merging**
