### PR TITLE
.only patch

### PR DESCRIPTION
**Pull request by tylerhjones**
patch for describe . only in response to https://github.com/mochajs/mocha/issues/1481

### CODE REVIEW

**Comment by dasilvacontin** [comment]
+1. Patch is an improvement until we develop the full fix.

**Comment by bjornstar** [comment]
LGTM, I think that it's a good idea to make `describe.only` match the behavior of `it.only`.

**Comment by dasilvacontin** [comment]
This patch doesn't work (yay our tests). You are only patching one of the interfaces and you are doing it in the *compiled* mocha file. The compiled mocha file is auto-generated from the lib for the releases.

You have to patch the following files:
* `interfaces/bdd.js`
* `interfaces/qunit.js`
* `interfaces/tdd.js`

**Comment by dasilvacontin** [comment]
ping @tylerhjones

**Comment by tylerhjones** [comment]
thanks for the info, ill work on it later tonight MST

**Comment by dasilvacontin** [comment]
Cool! I was just pinging in case you missed my message.

**Comment by tylerhjones** [comment]
This currently passes 'npm test', but I have not yet added a separate test to assert that this .only bug does not appear again.

**Comment by dasilvacontin** [comment]
The `mocha.js` file at the root of the repo shouldn't be modified; it is compiled from the source whenever a release is prepared.

Regarding test location, I should suggest adding tests for each of the interfaces at `test/acceptance/misc/only`.

Please squash your commits into a single one after the changes. Thanks!

**Comment by danielstjules** [comment]
Thanks for the PR! For issue #1481, it looks like the team has decided to go with https://github.com/mochajs/mocha/pull/1591 which fixes some related `only` bugs due to the use of RegExps. Appreciate you taking the time to work on this though!

**Comment by Vanuan** [comment]
I don't think that fixing multiple issues with one pull request is a good idea.
This is a good PR, it's just missing some tests.

**Comment by Vanuan** [comment]
#1591 is closed

**Pull request closed without merging**
