### PR TITLE
Add link checking to docs build step

### PR DESCRIPTION
**Pull request by Munter**
### Description of the Change

When the docs are being built, a link scanner will check that all internal links are pointing at things that exist, thus avoiding broken links and bad user experiences.

### Benefits

Easier to spot mistakes in docs.

### Possible Drawbacks

Longer build time

### CODE REVIEW

**Comment by outsideris** [comment]
In my local, below errors occurred. Did it happen only in my environment?
I looked the docs files but I didn't find any clue.

```
ok 7934 fragment-check docs/_site/api/browser_progress.js.html --> global.html#runWithSuite
ok 7935 fragment-check docs/_site/api/browser_progress.js.html --> global.html#util
not ok 7936 fragment-check docs/_site/api/Hook.html --> hook.js.html#line20
  ---
    operator: fragment-check
    expected: "id=\"line20\""
    actual:   null
    at: docs/_site/api/Hook.html:75:54 <a href="hook.js.html#line20">...</a>
  ...
not ok 7937 fragment-check docs/_site/api/Hook.html --> hook.js.html#line38
  ---
    operator: fragment-check
    expected: "id=\"line38\""
    actual:   null
    at: docs/_site/api/Hook.html:261:54 <a href="hook.js.html#line38">...</a>
  ...
not ok 7938 fragment-check docs/_site/api/hook.html --> hook.js.html#line20
  ---
    operator: fragment-check
    expected: "id=\"line20\""
    actual:   null
    at: docs/_site/api/hook.html:75:54 <a href="hook.js.html#line20">...</a>
  ...
not ok 7939 fragment-check docs/_site/api/hook.html --> hook.js.html#line38
  ---
    operator: fragment-check
    expected: "id=\"line38\""
    actual:   null
    at: docs/_site/api/hook.html:261:54 <a href="hook.js.html#line38">...</a>

.......

# Connecting to 0 hosts (checking <link rel="preconnect" href="...">
# Looking up 0 host names (checking <link rel="dns-prefetch" href="...">

1..8156
# tests 8156
# pass  7835
# fail  321
The script called "docs.linkcheck" which runs "hyperlink -ri --canonicalroot https://mochajs.org docs/_site/index.html" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "docs" which runs "nps docs.prebuild && nps docs.api && eleventy && nps docs.linkcheck && nps docs.postbuild" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```

**Comment by Munter** [comment]
@outsideris I have three same errors locally, and you can see them in the netlify build af well. Lots of broken links. But it seems like most of them are due to things that probably just need to be fixed in a single place in some template, or in jsdoc or or jsdoc theme

**Comment by Munter** [comment]
I don't quite understand why the netlify build is failing. Locally I have all link checks passing now.

**Comment by juergba** [comment]
What about this `acorn` dependency experiment, do we need this dependency finally?

**Comment by Munter** [comment]
Sadly it seems we do. There's something up with the way some acorn plugins are set up, which disallows the freshly released `acorn@7` to be used. It will probably take some time before the ecosystem stabilizes and upgrades all semver requirements to include major version 7

**Comment by juergba** [comment]
I cloned your branch and then `npm install`, which results in 272 vulnerabilities.
`npm audit fix` reduces the vulnerabilities down to two.

`npm start doc` does not work on my windows laptop. As a Window'er I'm used to results like that, so just a deep sigh of despair and resignation.
```
ok 7384 fragment-check docs\_site\api\runner.js.html --> global.html#util
not ok 7385 fragment-check docs\_site\api\Hook.html --> hook.js.html#line20
  ---
    operator: fragment-check
    expected: "id=\"line20\""
    actual:   null
    at: docs\_site\api\Hook.html:72:54 <a href="hook.js.html#line20">...</a>
  ...
not ok 7386 fragment-check docs\_site\api\Hook.html --> hook.js.html#line38
[...]
1..7580
# tests 7580
# pass  7384
# fail  196
The script called "docs.linkcheck" which runs "hyperlink -ri --canonicalroot https://mochajs.org docs/_site/index.html --skip 'id="line'"
failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```
On the remote branch I checked some of the links and they seem to be correct.

**Pull request merged**
