### PR TITLE
Add Var.CI integration

### PR DESCRIPTION
**Pull request by boneskull**
This pull request aims to demonstrate the power of [VarCI](https://var.ci/), the missing assistant for GitHub issues.
## 

_Automatic update by [Var.CI](https://var.ci)_

### CODE REVIEW

**Comment by boneskull** [comment]
@VarCI-bot what is this i don't even

**Comment by boneskull** [comment]
@VarCIbot wait--what's your name?

**Comment by jadb** [comment]
Hey @boneskull - not sure if it was you that brought this to my attention now but the project was listed on the homepage because the repo was connected. 

I see you have tried playing with it and it stalled. Anything I can help you with to maybe get this reviewed again?

**Comment by boneskull** [comment]
@jadb Thanks for following up.  We *do* have a need for a solution *like* Var.CI (though probably not even that powerful), but I'm dubious about using a closed-source SaaS product (even if it's free for open source; I can't find details on the pricing structure).  

I'd prefer to just download, configure, and run this type of bot on my own server.

**Comment by jadb** [comment]
After you said chat app blocked I remembered I had replied to one of your messages back in September and you had run into some bug (which got fixed the next day). My bad I didn't follow up by email. Chat app provider is supposed to do that when message does not reach you but apparently it does not.

-- 

Just read your next comment so I'll reply here. 

While I understand your concerns, there was no plans on having a private offering until we saw the demand (currently behind feature toggle). 

There was plans on open-sourcing the whole thing (ala-Travis) which stalled (not dropped) when we decided to offer private repo support. We might still reconsider that, and you'd be on top of my list of people to reach out to for feedback (if that's OK with you).

That been said, like some testing or styling CIs, may I ask why you prefer hosting the bot? I see your using services like AppVeyor and Travis' hosted version.

I hustle because it would be an honour and privilege to have MochaJS among the OSS projects that trust us. Don't blame me for going the extra mile 😄

**Comment by boneskull** [comment]
@jadb re Travis & AppVeyor:

1. They are both well-established and thusly low-risk
2. Last time I checked, AppVeyor is the only show in town for what it does
3. I don't have the expertise nor desire to safely configure, deploy and maintain--or pay for--our own CI server; the benefits of self-hosting are few

We have very, very few requirements for this type of bot.  If self-hosting turns out to be a rabbit hole, I'll look more closely at SaaS solutions--Var.CI will be on the list.  :smile:

**Comment by jadb** [comment]
Fair enough. My hope is to be well established at some point too, gotta start somewhere! 

I like to believe we are also unique in town (in terms of feature set) and have more in the pipeline (hopefully before the new year). Wished I could say more at this point but if you allow me, I won't hesitate to hustle again ;)

I just merged changes to remove the logo - CI systems will deploy in a few minutes.

Cheers!

**Comment by boneskull** [comment]
> UPDATE: in case it was unclear after latest changes on the website, even with a pricing structure in place, it will ALWAYS be free for OSS.

:+1:

> Chat app provider is supposed to do that when message does not reach you but apparently it does not.

I'm aggressively blocking many services via [uBlock Origin](https://github.com/gorhill/uBlock/).  Looking at my logs, I'm not seeing any requests to `*.smooch.io` blocked:

screenshot

My WAG is one of:

- ["Disable hyperlink auditing beacon"](https://github.com/gorhill/uBlock/wiki/Disable-hyperlink-auditing-beacon), or
- ["Disable pre-fetching"](https://en.wikipedia.org/wiki/Link_prefetching#Issues_and_criticisms)
- Smooch has to pass through New Relic/Segment/etc. to work properly.

Not sure if you care to ask Smooch about it, but mainly I was interested in discovering what was happening here.

**Pull request closed without merging**
