### PR TITLE
update mkdirp and yargs-parser dep to fix vulnerabilities (6.2 release)

### PR DESCRIPTION
**Pull request by sseide**
### Description of the Change

Mocha 6.2.x is latest version supporting Node versions below 12, therefor used by lots of projects needing this.
This version depends on two different packages which has security vulnerabilities: mkdirp and yargs-parser. This PR updates these two dependencies to the next higher version with fixes for these vulnerabilities and nothing else.

### Alternate Designs

Decided for this change to only change the minimum amount required for vulnerabilities flagged in production dependencies.

### Why should this be in core?

Without this PR all builds of projects using mocha and requiring successful running vulnerability checks like `npm audit´ are failing.

### Benefits

`npm audit` not failing for projects using mocha.

### Possible Drawbacks

none

### Applicable issues

* Is this a breaking change (major release)?  NO
* Is it an enhancement (minor release)?  YES
* Is it a bug fix, or does it not impact production code (patch release)? YES

New minor version should be released after accepting this PR.

### References

* minimist (dependency of mkdirp): https://www.npmjs.com/advisories/1179
* yargs-parser: https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381

Thanks,
Stefan Seide

### CODE REVIEW

**Comment by juergba** [comment]
This statement is not correct:
> Mocha 6.2.x is latest version supporting Node versions below 12

Which Node versions are you testing with?

**Comment by sseide** [comment]
looking at the release notes and changelog. There  are ony tags for 6.2 releases and 7.1 And 7.0 got no security update lately, only the 7.1 line.

7.1.0 states prominently in the changelog "Node.js only v12.11.0 and above". But (on a third read) it may want to say 12.x for some special conditions and not globally... So please correct me if im wrong...

**Comment by juergba** [comment]
> looking at the release notes and changelog. There are ony tags for 6.2 releases and 7.1 [...]

There are dozens of tags listed, I don't know where you are looking at.

> "Node.js only v12.11.0 and above" [...]

This is valid for ESM support.

**Comment by sseide** [comment]
> > looking at the release notes and changelog. There are ony tags for 6.2 releases and 7.1 [...]

> There are dozens of tags listed, I don't know where you are looking at.

Here i was referring to the git repository having a "release/6.2.x" and "release/7.1.x" but no "release/7.0.x" branch. Therefor this made me think the 7.0 line is gone an no maintenance or something  else any further. And 7.1 has the statement about Node 12 below ..

> > "Node.js only v12.11.0 and above" [...]

> This is valid for ESM support.

Ok, as i understand now this min requirement is not global for mocha itself.

Shall i close the PR than? 6.x line of releases is out of maintenance? Fine for me when upgrade to latest 7.1 is possible with Node 10.x

**Comment by karlhorky** [comment]
I would like to also voice my support here - would be nice to backport security vulnerability fixes to the 6.x versions, for those projects using v6.

**Comment by juergba** [comment]
@sseide No, please leave the PR open for now.

@karlhorky we don't maintain LTS releases. The last release (v7.1.1) is normally the only maintained version. We haven't decided yet, wether we backport the security fix to v6.2.2.

**Comment by sseide** [comment]
Calling `npm audit --production` or running the snyk.io vulnerability checks for production dependencies only does not show vulnerabilities anymore. Everything is green.

```
$ npm audit --production
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 169 scanned packages
```

Checking with devDependencies (e.g. `npm audit`) its reporting much lower problems now. But having devDependncies without errors is not really needed. The production dependencies are much more important...

```
$ npm audit
                                                                                
                       === npm audit security report ===   
...
found 47 vulnerabilities (12 low, 2 moderate, 33 high) in 29906 scanned packages
  run `npm audit fix` to fix 15 of them.
  1 vulnerability requires semver-major dependency updates.
  31 vulnerabilities require manual review. See the full report for details.
```

**Comment by juergba** [comment]
@sseide your last commits don't make any sense.
Please read [npm](https://docs.npmjs.com/configuring-npm/package-lock-json.html). 
Key statement: `One key detail about package-lock.json is that it cannot be published [...]`

**Comment by sseide** [comment]
@juergba yes you are right. Was too late this day and forgot this is not published to npm.
Just seen this file is part of the git-repo (see https://github.com/mochajs/mocha/tree/release/v6.2.x) and people checking it out will get dozen of old dependencies..

**Comment by sseide** [comment]
but at least the changes to the package.json will fix problems for others, as these versions listed as "dependencies" are free of known security problems. Therefore you do not have to backport your code changes to replace mkdirp package with other implementations... It may be less intrusive.

**Comment by juergba** [comment]
We published mocha@6.2.3.

**Pull request closed without merging**
