### PR TITLE
feat(interfaces/*): support untitled suites/tests #1632

### PR DESCRIPTION
**Pull request by a8m**
Further to issue #1632, I created this draft.
let's discuss about it.

### CODE REVIEW

**Comment by travisjeffery** [comment]
the other option would be to throw an error with a good message, that would probably result in better practices/readable tests imo

**Comment by a8m** [comment]
So there are two options:
1. use a fallback title - `Untitled suite/test`
2. throw an error with a usage message (it means to failing, and not run at all).
Please correct me if I get you wrong @travisjeffery 

I prefer the second option, but the first one is more forgiving.
/cc @dasilvacontin

**Comment by travisjeffery** [comment]
yeah let's go with throwing an error. i'd rather be opinionated on having people do the right thing.

**Comment by dasilvacontin** [comment]
Yeah, I also prefer throwing an error. As @travisjeffery, said, leads to more readable code and enforces good practice, and it's probably what you wanted to do anyways.

**Comment by a8m** [comment]
ping

**Comment by danielstjules** [comment]
I like the solution. It supports the possibility of creating interfaces that accept empty titles for either suites, tests, or both as well.

**Comment by a8m** [comment]
Thanks @danielstjules 
:smile:

**Comment by a8m** [comment]
I started to implement it on the interfaces side, but then I got the feeling of repeating myself.

**Comment by danielstjules** [comment]
Yea, updating it at the suite/test level is good, since any interfaces can just use an empty string for the name if they'd like to accept "anonymous specs" :)

**Comment by dasilvacontin** [comment]
Was is possible to use an object as a title before? That was later being converted to a string inside our code.

Because if that was possible before, this should be considered breaking. Or we should check for a `.toString()` or something.

**Comment by a8m** [comment]
Using object as suite/test-case title, returning this result (is just `toString` it):
```sh
suite
    ✓ [object Object] 
```
>  this should be considered breaking.

fair enough, I added it to `v3.0.0` milestone

**Comment by danielstjules** [comment]
``` javascript
$ cat example.js
it({foo: 'bar'}, function() {});

$ mocha example.js


  ✓ [object Object]

  1 passing (8ms)
```

``` javascript
$ cat example.js
it(12, function() {});

$ mocha example.js


  ✓ 12

  1 passing (8ms)
```

**Comment by dasilvacontin** [comment]
But what if you accept objects that have a `.toString()` or are not a function?

**Comment by danielstjules** [comment]
@dasilvacontin Because mocha currently works with functions, too.
``` javascript
$ cat example.js
it(function() {}, function() {});

$ mocha example.js


  ✓ function () {}

  1 passing (9ms)
```

I don't personally see this PR as breaking the API and requiring a new major release. Minor would be fine, and would probably be a good fit for 2.3.0 or 2.4.0. It's unspecified behavior. We shouldn't be concerned if someone is relying on passing objects or functions as the spec or suite titles, rather than strings. The API documents that the title should be a string: https://github.com/mochajs/mocha/blob/master/lib/suite.js#L25 https://github.com/mochajs/mocha/blob/master/lib/suite.js#L43 https://github.com/mochajs/mocha/blob/master/lib/test.js#L16

**Comment by dasilvacontin** [comment]
I agree that this does not break the API. But if you make people waste time, you are doing the same harm; you don't want someone's build to suddenly stop working and make them waste time tracking down the issue to fix it.

**Comment by a8m** [comment]
> you don't want someone's build to suddenly stop working and make them waste time tracking down the issue to fix it.

So that's the reason we added this user-friendly message :)

**Comment by dasilvacontin** [comment]
> that's the reason we added this user-friendly message :)

User-friendly message that breaks your build and makes you correct hundreds of tests in the worst case scenario.*

**Comment by a8m** [comment]
We are not breaking the API, this is just a weakness that maybe users take advantage of it.

/cc @travisjeffery

**Comment by danielstjules** [comment]
http://symbolhound.com/?q=it%28%22 / http://symbolhound.com/?q=it%28%27 vs http://symbolhound.com/?q=it%28%7B / http://symbolhound.com/?q=it%28function (the only actual match is a typo) I wish I could find a search engine with better support for symbols lol Any suggestions?

So for:
``` javascript
it(function() {}, function() {
});
it({foo: bar}, function() {
});
it(-1, function() {
});
```
it's still undefined behavior, since the public API docblocks (https://github.com/mochajs/mocha/pull/1634#issuecomment-87801546) specify that title should be a string, and nowhere on http://mochajs.org/ do we mention non-string titles are supported.

@dasilvacontin I hear what you're saying about preserving BC, and agree for the most part, but the issue you highlighted in mustache.js seems to be of a different scope. That said, if a 3.0.0 release is in the works for the coming months, I'm not worried either way. :)

**Comment by dasilvacontin** [comment]
Those queries can't come up with the edge-cases I mentioned.

Still, I agree that the number of people who could be affected by this is very very low. And afaik, since we have some *serious* bugs in mocha (eg #534), I wouldn't bump to v3 solely for this reason, since not getting more bugfixes in v2 would probably out-harm the problems merging this PR could cause.

In the case we were soon bumping to v3, I'd include this for the next major.

**Comment by boneskull** [comment]
imo, If it throws exceptions where it didn't throw exceptions before, it's not backwards-compatible and needs to wait until a major.

**Comment by a8m** [comment]
> it's not backwards-compatible and needs to wait until a major.

fair enough.

**Comment by boneskull** [comment]
@a8m this needs rebasing against v3.0.0 as well

**Comment by a8m** [comment]
Replaced with #1809(rebased on top of v3.0.0)

**Pull request closed without merging**
