### PR TITLE
Use the correct option to handle the global error

### PR DESCRIPTION
**Pull request by amsul**

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Hi! Thanks for the PR!

Could you revert the changes on the `mocha.js` file? We only rebuild it for releases. Ty!

**Comment by amsul** [comment]
@dasilvacontin done 👍

**Comment by dasilvacontin** [comment]
I'll try adding tests for this one.

**Comment by dasilvacontin** [comment]
If anyone wants to write the tests for this one, feel free – otherwise I'll get around it some day, I guess.

**Comment by boneskull** [comment]
I don't know what prompted this PR, or if it fixes a bug, or what. @amsul, can you comment?  Thanks for the PR!

**Comment by amsul** [comment]
@boneskull this fixes a small bug in the feature I introduced: https://github.com/pumpupapp/mocha/commit/92dfdd420ff2f611bae6582a25d79681b5271546

Only thing I didn't realize at that time was that `allowUncaught` is set as a boolean property on a `Runnable` and `Runner`, but not on `mocha`.

On `mocha`, the property is a method that returns the boolean option: https://github.com/pumpupapp/mocha/commit/92dfdd420ff2f611bae6582a25d79681b5271546#diff-aa849a970cef551664c12f04a4209f6fR430

So, this fixes that by using `mocha.options.allowUncaught` instead. Another fix would've been to actually invoke `mocha.allowUncaught()`.

@boneskull hope that clarifies things a bit!

**Comment by amsul** [comment]
I guess this now conflicts because the `browser-entry.js` file has been moved to a new location: https://github.com/mochajs/mocha/blob/master/browser-entry.js

**Comment by boneskull** [comment]
@amsul If you can resolve the conflict(s), that'd be helpful!

**Comment by amsul** [comment]
@boneskull here you go! https://github.com/mochajs/mocha/pull/2474 👍

**Pull request closed without merging**
