### PR TITLE
Updates mocha.js to address #1700

### LINKED ISSUE #1700: "PhantomJS timed out, possibly due to a missing Mocha run() call" regression
I'm getting a
```
Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.
```
after upgrading mocha from 2.1.0 to 2.2.0 (or any of the 2.2.x series, including the most recent 2.2.5 release).

I've managed to track it to 521b7e443e3a0feed3091c0378973c4faab42160, specifically, lines 4485-4488:
```js
    // Discard the resolution if this test has already failed asynchronously
    if (self.state) return;
```
Commenting out `if (self.state) return;` eliminates the error (I've tested against mocha 2.2.0 and 2.2.5).

# Steps to reproduce:
Disclaimer: I never used mocha, grunt, yeoman, bower, or npm prior to two weeks ago, so I fully accept that the problem lies solely with how I'm testing rather than a problem with mocha itself. That said, I noticed this problem using Yeoman's generator-webapp after updating mocha in bower.json from 1.14.0 to 2.2.4. Dropping to v2.1.0 fixed the issue.
I've pushed a stripped-down, minimal version of an "app" that reproduces the problem: https://github.com/eddies/mocha-test-case

```
git clone git@github.com:eddies/mocha-test-case.git
cd mocha-test-case
npm install && bower install
grunt test
```
Comment out line 4512 of `bower_components/mocha/mocha.js` and re-run `grunt test` for the test to now pass.

### PR DESCRIPTION
**Pull request by eddies**
Fixes #1700

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Hi @eddies! Could you provide tests that pass thanks to this change? Cheers!

**Comment by eddies** [comment]
@dasilvacontin Honestly, I'm not sure how to provide a unit-like test for this. I was only triggering this issue as part of running a test w/ PhantomJS and Grunt and and various other dependencies. I did create https://github.com/eddies/mocha-test-case as a minimal example, which I believe definitively isolates the error to the specific one-line commit to mocha I highlighted.

If someone could take a look at the mocha-test-case repo and provide some suggestions as to how that might be translated into a test for the mochajs repo, I could try running with it from there.

**Comment by danielstjules** [comment]
@eddies Please make the change against runnable.js, rather than the compiled/disted mocha.js. https://github.com/mochajs/mocha/blob/49d81aa17751e47cec26a22f0607076c98c4a1fc/lib/runnable.js#L215

Beyond that, how does this impact https://github.com/mochajs/mocha/pull/1578 and https://github.com/mochajs/mocha/pull/1540 ? After updating runnable.js, I wonder if the build fails.

**Comment by jbnicolai** [comment]
Picked up @danielstjules's comment and merged in a separate branch.

**Pull request closed without merging**
