### PR TITLE
Add mocha.js to .gitignore

### PR DESCRIPTION
**Pull request by dasilvacontin**
Makes contributing more dev-friendly, specially for newcomers to the
project.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
Meh, .gitignore only affects untracked files. My bad.

**Comment by boneskull** [comment]
no, this is a good idea, it just needs more pieces:

- add `mocha.js` to `files` prop of `package.json`
- `git rm mocha.js`
- add `mocha.js` to `.gitignore`
- add `prepublish` script `make mocha.js`

this will ensure `mocha.js` is built and packaged when releasing.

**Comment by boneskull** [comment]
actually looks like we're using an `.npmignore`.  I'll convert it to `files`

**Comment by boneskull** [comment]
ehh we are using both, we only need one--I'll remove `.npmignore`

**Comment by dasilvacontin** [comment]
I thought we had the browser bundle in git for people to download it from the repo or something.

**Comment by boneskull** [comment]
> I thought we had the browser bundle in git for people to download it from the repo or something.

I don't know why.  You can download it with zip files or whatever.  But if you need the latest version and happen to be on a system without `make`, or stuck with an old `npm`, you're kind of screwed.  

See #2268.  I almost want to roll that into this; it shouldn't take too long to just convert the targets to npm scripts... 😛

**Comment by boneskull** [comment]
I think we can get away with just making the `mocha.js` target an npm script for now

**Comment by boneskull** [comment]
(squashed)

**Comment by boneskull** [comment]
amended

**Comment by boneskull** [comment]
actually nevermind.  we lose bower support if we remove the artifact from vcs.

**Comment by ScottFreeCode** [comment]
Bower looks at the specific release, right? So we could check it in for the release commit, then delete it in the first commit to master after the release?

**Comment by boneskull** [comment]
@ScottFreeCode bower doesn't look at anything except VCS tags, which means you have to include your build artifacts in VCS.  some projects make a separate repo just for this.  npmcdn.com is another option, but I couldn't get it working trivially (try `bower install https://npmcdn.com/mocha@2.4.5/bower.zip`; I was getting a HTTP 500)

**Comment by ScottFreeCode** [comment]
I mean, could we explicitly add it (overriding .gitignore) only in the tagged commits for each release and then take it back out in the next commit after so it's in VCS for Bower looking at the tags but .gitignore keeps people from committing it in general?

**Comment by boneskull** [comment]
@ScottFreeCode that seems like a pain in the butt 😛

**Comment by dasilvacontin** [comment]
Also, think of cdnjs.

**Pull request closed without merging**
