### PR TITLE
Fix/improve es3 compat

### PR DESCRIPTION
**Pull request by boneskull**
see #2259 for original PR.

### CODE REVIEW

**Comment by boneskull** [comment]
I'll squash my contribution

**Comment by ScottFreeCode** [comment]
Looks good to me.

**Comment by dasilvacontin** [comment]
Any reason `JSON` is not imported in:
- `lib/reporters/json-stream.js`
- `lib/reporters/json-cov.js`

?

**Comment by ScottFreeCode** [comment]
Would they be used in-browser in any way?

**Comment by boneskull** [comment]
@ScottFreeCode maybe headlessly.

**Comment by boneskull** [comment]
@ScottFreeCode in the future you can simply rebase the branch onto `master`, unless you are philosophically opposed to such a thing

**Comment by ScottFreeCode** [comment]
I do generally rebase my own branches rather than merging updates; in this case I just wasn't sure if I should mess with ndhoule's commit.

Either way, looks like this is ready to roll? (Or as ready as it will be once we work out any unrelated Windows/AppVeyor kinks...)

**Comment by boneskull** [comment]
fixed in v3.0.0 branch by af9e297be7ea90b04672aebe3cd9822d667a62c8, 39ba880da7620fe392664d67f352637ab7cbb58f and d7c459b323d7637657cafbcae5210b14a63e3521.

**Pull request closed without merging**
