### PR TITLE
Add `utils.escape` tests and fix unicode escaping

### PR DESCRIPTION
**Pull request by jkrems**
I started walking down the path of replacing those myself but once I hit surrogate pairs it seemed to become silly. That's why I went with just adding `he`.

Fixes https://github.com/mochajs/mocha/issues/2955

### CODE REVIEW

**Comment by boneskull** [comment]
@jkrems Thanks!!

**Comment by JamesMGreene** [comment]
The `{ useNamedReferences: true }` part of this PR breaks the XUnit reporter, which now outputs things like `&grave;` (which is only valid in HTML, not XML).

**Comment by jkrems** [comment]
Oops, could've anticipated that. @JamesMGreene can you confirm that setting that option to false fixes everything? I'll assume that we could live with slightly uglier `&quot;` escaping as long as the files are all valid.

**Comment by jkrems** [comment]
Assuming that we're fine with "ugly" escapes for now, there's a potential fix in https://github.com/mochajs/mocha/pull/3003 now. @JamesMGreene Can you give that branch a try to verify that it fixes your issue?

**Pull request merged**
