### PR TITLE
closes #3787 Allow passing multiple node flags

### LINKED ISSUE #3727: Config file schema
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Is there a schema or declaration for mocha's new config file, so that we get tooling?  Could be a JSON schema, TypeScript declarations, or both.

It can be declared in one form and compiled to the other via quicktype.
https://www.npmjs.com/package/quicktype
https://app.quicktype.io/?share=x6K1P6RGhC3tAxYP9tgm

**Expected behavior:** [What you expect to happen]

Here's a usage example, if such declarations existed.

`.mocharc.json`
```json
{
    "$schema": "https://mochajs.org/schemas/rc.json",
    // tooltips with descriptions and defaults available here
}
```

`.mocharc.js`
```js
module.exports = /**@type Mocha.Rc */({
    // tooltips with descriptions and defaults available here
});
```

### Versions

mocha@next

### LINKED ISSUE #3787: Cannot pass multiple node flags
With a simple mocharc.json:
```
{
  "max-old-space-size": 4096,
  "v8-allow-natives-syntax": true
  ...
}
```
I get the error
```Error: illegal value for flag --max-old-space-size=4096 --allow-natives-syntax of type size_t```

### PR DESCRIPTION
**Pull request by aginzberg**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

Fixes support for multiple node flags. Previously, the node flags were splatted onto a single string rather than separate elements in an array of strings.

### CODE REVIEW

**Comment by juergba** [comment]
closes #3727 or #3787 ?
Please complete the title with some useful information.

**Comment by aginzberg** [comment]
Updated, sorry for the confusion.

**Comment by dex4er** [comment]
Hi. When mocha with this will be released? I have to stay with Mocha 5.x.x because of this bug in 6.x.x :(

**Comment by outsideris** [comment]
@dex4er Not yet. This will be included in [6.1.0](https://github.com/mochajs/mocha/milestone/27?closed=1)

**Pull request merged**
