### PR TITLE
build mochajs.org with Jekyll; closes #1640

### LINKED ISSUE #1640: jekyll gh-pages
This is in progress.  If anyone knows how I can use syntax highlighting *and* valid GFM markdown in Jekyll, please let me know.

### PR DESCRIPTION
**Pull request by boneskull**
Lots of stuff here, but the main things:

- use Jekyll
- convert `index.md` to *actual GFM Markdown*
- a lot of edits of the documentation, including, but not limited to:
  - reorganization
  - grammar fixes
  - code style fixes
  - rewording confusing sentences
  - add a couple more examples
  - dynamically generate TOC
  - use CDNs for JS, though there's basically none

I've taken every effort to make the site look as close to the current version as it does now, and keep it compatible with old browsers.  However, I was not able to reuse the syntax highlighting scheme, as highlighting is now done by Pygments.

screenshot 1

screenshot 2

*Note*: Currently this uses my fork of the `github-pages` gem, because the production one has a couple problems, including a significant security hole.

### CODE REVIEW

**Comment by boneskull** [comment]
:bow:

**Comment by danielstjules** [comment]
:clap:

**Comment by boneskull** [comment]
OK, this is building fine locally, but not on gh-pages, so not sure why

**Comment by boneskull** [comment]
I'm going to close this for now until I can figure it out

**Comment by dasilvacontin** [comment]
We don't have Travis executing gh-pages PRs? hmm

**Comment by boneskull** [comment]
I did see a failure

On Fri, Apr 17, 2015 at 9:26 AM, David da Silva Contín <
notifications@github.com> wrote:

> We don't have Travis executing gh-pages PRs? hmm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mochajs/mocha/pull/1657#issuecomment-94021234>.
>



-- 
-- 
Christopher Hiller
http://boneskull.com

**Pull request closed without merging**
