### PR TITLE
exclude auto-generated contents from docs/index.md; closes #3713

### LINKED ISSUE #3713: keep auto-generated content in docs out of VCS
Our documentation has automatically generated sections.  The content in these sections is part of the doc build and should not be in VCS.

```html
<!-- AUTO-GENERATED-CONTENT:START (toc:maxdepth=2&bullets=-) -->
(stuff)
<!-- AUTO-GENERATED-CONTENT:END -->
```

Should *not* be modified when running `npm start docs`.

Instead, the build should be run against a transient copy of the file.  That means:

1. Copy `docs/index.md` to a temp location
1. Run [the preprocess script](https://github.com/mochajs/mocha/blob/e01a54eb2e5d28104625c15df641801747533b63/package-scripts.js#L284) against the temp copy
1. Ensure Eleventy generates documentation from the temp copy
1. Remove the temp copy

Take care not to deploy the temp copy itself; Eleventy should deploy HTML only, and no markdown.

(This also applies to tutorials found in the API docs, which are in incoming pull request #3655; don't worry about these for now.)

### PR DESCRIPTION
**Pull request by wanseob**
### Description of the Change

- Remove auto-generated contents from docs/index.md
- Make docs/index.md keep excluding auto-generated contents
    1. At the pre-processing stage, copy docs/index.md to docs/index.md.tmp
    2. Trap exit signals and recover docs/index.md with docs/index.md.tmp after the script execution
- Add docs/index.md.tmp to the .gitignore list

### Benefits

No more frustrating jobs after `npm start docs`.

### Applicable issues

This PR handles #3713

### CODE REVIEW

**Comment by boneskull** [comment]
@wanseob I've resolved the conflicts and rebased this branch onto `master`.

**Comment by wanseob** [comment]
Appreciate your feedback and rebasing @boneskull. I added a new commit to remove the tmp file at the post-processing step. But I'm wondering that isn't it enough to exit with code 0 when it executes `md-magic --config ./scripts/markdown-magic.config.js --path docs/index.md.tmp` to ensure. If not, how can we ensure elevanty processed `docs/index.md.tmp`?

**Comment by JoshuaKGoldberg** [comment]
👋 coming back to this @wanseob, are you still interested in working on this PR? As of https://github.com/mochajs/mocha/issues/5027 there are again maintainers who can review it now. No worries if you no longer have time - but if you do that'd be great!

**Comment by JoshuaKGoldberg** [comment]
Closing out to keep our queue small. Someone please yell at me if this should be re-opened though. Cheers! 🤎

**Pull request closed without merging**
