### PR TITLE
fixing hook failure behaviour, solves #534

### PR DESCRIPTION
**Pull request by dasilvacontin**
wip

### CODE REVIEW

**Comment by boneskull** [comment]
@dasilvacontin Why is this a PR if it's a WIP? :smile:

**Comment by dasilvacontin** [comment]
Never mind, I guess I got too excited or something. :sweat_smile:

**Comment by travisjeffery** [comment]
i'm fine with it, just put wip in the title or something and make it clear that it's not ready to go. it's a good way to get feedback before wasting a bunch of time on something that's not gonna get in.

**Comment by dasilvacontin** [comment]
@travisjeffery that was my initial intention, to show I'm actively working on it and maybe get some comments, but I'm still trying to figure out stuff. Async errors are being a total mess atm.

**Pull request closed without merging**
