### PR TITLE
Support --harmony_classes flag for io.js

### PR DESCRIPTION
**Pull request by jordansexton**

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR!

Given the number of harmony flags we're introducing, I wonder if it might be worth re-organizing the way we handle them. `--help` is getting pretty cluttered.

**Comment by danielstjules** [comment]
Could you squash your commits? :)

**Comment by jordansexton** [comment]
Done!

**Comment by danielstjules** [comment]
Great, thanks!

**Comment by jordansexton** [comment]
Thank you!

**Pull request merged**
