### PR TITLE
Feature ignore file #2036

### PR DESCRIPTION
**Pull request by megagon**
Please take a look at the implementation.
Let me know if that's ok - i will make tests for this. If need something to change - i will change.
After this i am going to add support to ignore files/suites/folders etc...

Tests passed locally.

### CODE REVIEW

**Comment by boneskull** [comment]
@megagon Hi, thanks for this.  As you can see in #2036, nobody replied to your question.  We are spread pretty thin at the moment.  

I'm not very enthusiastic about adding features at the moment, and we're not going to release until we get some browser coverage.  IMO any changes before the rewrite should probably just be bug fixes.  But others can weigh in...
 
cc @mochajs/mocha

**Comment by boneskull** [comment]
@megagon We do have browser coverage now and have since released, so we can revisit this.

I have a few comments:

1.  The default file should be `.mochaignore`
2.  It should support a global `mochaignore` file installed at whatever `npm get prefix` is
3.  It should support a per-user `~/.mochaignore`
4.  It should be based upon [ignore](https://www.npmjs.com/package/ignore) as to work how users would expect

Thanks for the PR!

**Comment by ScottFreeCode** [comment]
FWIW, I've discovered that you can actually accomplish exclusion, albeit cryptically and not as easily, using Glob with Mocha as-is: https://github.com/mochajs/mocha/issues/1577#issuecomment-225409794

**Comment by boneskull** [comment]
Closing for inactivity

**Pull request closed without merging**
