### PR TITLE
ammended for deprecated customFds option in child_process

### PR DESCRIPTION
**Pull request by taddei**
I found myself having to patch this up and I thought it might help others too.

### CODE REVIEW

**Comment by rfink** [comment]
+1 needed

(also https://www.npmjs.org/package/compare-version is no longer maintained)

Cheap plug for https://www.npmjs.com/package/version-compare.js

**Comment by marcooliveira** [comment]
@boneskull 0.12.0 has been released, and we're getting `child_process: customFds option is deprecated, use stdio instead.`. Maybe it's time for that upgrade?

**Comment by dasilvacontin** [comment]
And we are not supporting node 0.4.x anymore, which was the holdoff.

**Comment by jbnicolai** [comment]
:+1: afaik

**Comment by boneskull** [comment]
Yup.

**Pull request merged**
