### PR TITLE
Replace __proto__ references with inherits module

### PR DESCRIPTION
**Pull request by ndhoule**
cc @boneskull @jbnicolai 

Resolves https://github.com/mochajs/mocha/issues/1728.

Depends on merging https://github.com/mochajs/mocha/pull/1727 because it pulls in an npm dependency; uses style from https://github.com/mochajs/mocha/pull/1750

### CODE REVIEW

**Comment by boneskull** [comment]
I think I'd rather go with LoDash here, since there's going to be a ton of other shims we can replace it with.  @mochajs/mocha thoughts?

**Comment by ndhoule** [comment]
Which lodash function would you use here? `_.create`?

**Comment by ndhoule** [comment]
@boneskull Refactored this to use `lodash.create`, which can easily be swapped out for a full `lodash` when necessary. I think this version is less expressive than the `inherits` version but meh

**Comment by boneskull** [comment]
@ndhoule why do you feel it's less expressive?

**Comment by jbnicolai** [comment]
@nathanboktae I agree
@boneskull `create(..., {constructor: ...})` seems less expressive than `inherit(..., ...)`.

On the other hand, since we're intending to go with lodash anyways, I say we merge this version :)

Perhaps to make this a bit nicer we could refactor it into a utility method in `Base`

```javascript
function inherit(prototype, constructor) {
  return create(prototype, {
    constructor: constructor
  });
```

But no strong feelings about that.

**Comment by ndhoule** [comment]
haha pretty much exactly what @jbnicolai said, but really I don't care—I say merge it as is, it's certainly better than the `__proto__` version

**Comment by jbnicolai** [comment]
Agree, still a huge improvement :+1:

**Pull request merged**
