### PR TITLE
Remove stdout: prefix from browser reporter logs

### PR DESCRIPTION
**Pull request by Bamieh**
As noted by @plroebuck `level` is not used, should be `label` instead.

https://github.com/mochajs/mocha/commit/37193a432119be643b9476f97da557a6f60b7d0f#commitcomment-30530038

### CODE REVIEW

**Comment by plroebuck** [comment]
Do Mocha's current browser tests demonstrate the issue?

**Comment by plroebuck** [comment]
Maybe rename the PR as "Remove stdout: prefix from browser reporter logs"?

**Comment by Bamieh** [comment]
@plroebuck i don't think so, not sure how we'd test it though

**Comment by outsideris** [comment]
Now, I doubt #3445 is related this problem. In my test, I didn't found the `stdout:` problem.

**Comment by plroebuck** [comment]
Can now confirm problem exists in Mocha-5.2.0.
Here are my [steps to reproduce it](https://github.com/mochajs/mocha/issues/3521#issuecomment-431554817).

**Comment by plroebuck** [comment]
### Description of the Change

Removes stdout: prefix from reporter output in browser console.

### Why should this be in core?

N/A

### Benefits

Less onscreen noise for people who decide to run reporters _other_ than `HTML` reporter.

### Possible Drawbacks

Well, it's been around for a while now. People _may_ have written tests that work around the problem.

### Applicable issues

Fixes #2095
Fixes #3521 
semver-patch

**Pull request merged**
