### PR TITLE
chore: upgrade (most) depedencies to latest 

### PR DESCRIPTION
**Pull request by AviVahl**
### Description of the Change

- Upgraded (most) dependencies to latest stable version. Several ones are still outdated until dropping Node 6. Regenerated `package-lock.json`.
Now uses `coffeescript` instead of the deprecated `coffee-script`.

### Alternate Designs

Consider using dependabot or greenkeeper.

### Benefits

Less duplications in user's node_modules. Latest fixes and improvements in packages.

### Possible Drawbacks

Obviously, new versions could also introduce unknown new breakages.

### Applicable issues

Not breaking.

### CODE REVIEW

**Comment by AviVahl** [comment]
The original `coffeescript` package has been deprecated by its author, saying it moved to `coffee-script`. I'm not sure what's the benefit of testing the deprecated package instead of the currently-used one.

The upgrades are not "just because". There are upstream fixes in those third parties to use-cases you wouldn't necessarily test/account for. There's also the number of duplicate files (in user's node_modules) caused by `mocha` pinning third-parties to older versions.

**Comment by AviVahl** [comment]
not sure why my last comment is showing at the top :/

**Comment by juergba** [comment]
I think we should merge this. The sooner the better, so we could catch potential breakages in time, before cutting the next release.

**Comment by AviVahl** [comment]
Updated PR again. `npm audit` results improved as well.

`master`: found 7 vulnerabilities (2 low, 3 moderate, 2 high)
`branch`: found 3 vulnerabilities (1 low, 2 moderate)

AppVeyor failed due to failing to download Node. Appears to be a CI issue unrelated to this PR. Can anyone re-run it?

**Comment by juergba** [comment]
There is a saucelab IE11 error, restarts do not succeed. Is Karma upgrade the guilty one?

**Comment by AviVahl** [comment]
How do I run the same tests that run on master? Why aren't PRs tested 1:1 the same way master does?

**Comment by juergba** [comment]
By pushing your branch directly to this repo, not yours. Do you have permission to do that as a contributor?
I don't know.

**Comment by AviVahl** [comment]
I'll check and report back... Thx.

**Comment by AviVahl** [comment]
@juergba I have no permissions to push a branch to this repo. Would it be possible to activate SauceLabs tests for PRs originating from forks?

**Comment by juergba** [comment]
@AviVahl I'm really sorry, I have no idea how to achieve this.

I can push your branch for you, just tell me when you are ready.
I did something similar with PR3915. This PR is based on a forked repo, then I pushed the same branch directly to this repo. And the Saucelabs tests did run...
I apologize for this inconvenient procedure. We also have a time shift.

**Comment by AviVahl** [comment]
I'll try to get my hands on a Windows machine on Sunday and check it out manually. Thx.

**Pull request merged**
